### PR TITLE
Fix RelInput#getString doc's spell mistakes

### PR DESCRIPTION
**Pull request by LiShuMing**

### CODE REVIEW

**Comment by MGelbana-Incorta** [comment]
Please apply the contribution guidlines mentioned [here](https://calcite.apache.org/develop/#contributing).

This implies mentioning the Jira name in the pull request title and commits.

**Comment by LiShuMing** [comment]
I think it's a small spelling mistake, and may no need to create a `jira` any more.

**Comment by MGelbana** [comment]
Sorry I deleted my previous message.
To not loose context here, I was asking @LiShuMing to apply the guidelines [here](https://calcite.apache.org/develop/#contributing).

But I believe he's correct, it's a trivial change.

**Comment by zhztheplayer** [comment]
I am closing this - @LiShuMing, feel free to notify someone to review again when you are ready.

**Pull request closed without merging**
