### PR TITLE
Remove repeat `the` in java doc

### PR DESCRIPTION
**Pull request by strongduanmu**

### CODE REVIEW

**Review by chunweilei — APPROVED** [review]
LGTM

**Comment by strongduanmu** [comment]
@chunweilei Thanks a lot for your review.

**Comment by chunweilei** [comment]
@strongduanmu Thank you for your PR! 

P.S. I fix up the commit message.

**Comment by strongduanmu** [comment]
Thank you @chunweilei, I will contribute more to calcite community.

**Pull request closed without merging**
