### PR TITLE
[CALCITE-5501]: Fix flaky test by using XmlUnit

### PR DESCRIPTION
**Pull request by clesaec**
To fix [CALCITE-5501](https://issues.apache.org/jira/browse/CALCITE-5501), i propose to use XmlUnit; that is more accurate to compare XML files.

### CODE REVIEW

**Comment by asolimando** [comment]
@clesaec, thanks for taking a crack at it, can you also fix the commit message to match the Jira ticket's title please? I think it's even OK to force push since nobody has started reviewing, if needed, otherwise it can be done during the final squash right before merging.

**Comment by clesaec** [comment]
@asolimando : ok, squash done with a better commit message.

**Comment by rubenada** [comment]
@clesaec @asolimando is this PR still relevant? Shall we close it? It seems its Jira ticket was already resolved in the last release.

**Comment by asolimando** [comment]
> @clesaec @asolimando is this PR still relevant? Shall we close it? It seems its Jira ticket was already resolved in the last release.

Thanks @rubenada for the reminder, I am closing it as it's been superseded by #3049 (already merged and released)

**Pull request closed without merging**
