### PR TITLE
[CALCITE-6427] Use a higher precision for DECIMAL intermediate results for some aggregate functions like STDDEV

### PR DESCRIPTION
**Pull request by mihaibudiu**
@zabetak hopefully this PR will fix the problem of STDDEV requiring a higher declared precision when combined with #3733

### CODE REVIEW

**Comment by mihaibudiu** [comment]
No tests were affected because today casts to decimal values are noops.

**Comment by mihaibudiu** [comment]
I will try this commit in combination with #3733 to see whether it handles STDDEV. If it does, I will merge this one first, then amend #3733, and then hopefully merge that one too.

**Comment by mihaibudiu** [comment]
Does anyone want to review this PR?
This is blocking some other more important PRs, and it's not too complicated.

**Comment by NobiGo** [comment]
> Does anyone want to review this PR? This is blocking some other more important PRs, and it's not too complicated.

I will review in the next week.

**Comment by NobiGo** [comment]
Strangely, we don't need to change any unit test.

**Comment by NobiGo** [comment]
> I will try this commit in combination with #3733 to see whether it handles STDDEV. If it does, I will merge this one first, then amend #3733, and then hopefully merge that one too.

This PR works good with #3733 ?

**Comment by NobiGo** [comment]
Use a higher precision for DECIMAL by precision*2 and scala*2, Do we refer to any database or  SQL standard？I just want to confirm.

**Comment by mihaibudiu** [comment]
> Strangely, we don't need to change any unit test.

That is because casts to decimal have no effect

**Comment by mihaibudiu** [comment]
> Use a higher precision for DECIMAL by precision_2 and scala_2, Do we refer to any database or SQL standard？I just want to confirm.

This is independent on the database. It is three enumerable implementation. Arguably, some of these choices should be part of the type system.

**Comment by mihaibudiu** [comment]
> > I will try this commit in combination with #3733 to see whether it handles STDDEV. If it does, I will merge this one first, then amend #3733, and then hopefully merge that one too.
> 
> This PR works good with #3733 ?

The current version of #3733 includes this pr. This shows that this pr solves the problem for stddev but not for other aggregates like variance. I still want to merge this first.

**Comment by mihaibudiu** [comment]
In the interest of unblocking #3733 I will merge this and rebase the other PR.

**Pull request merged**
