### PR TITLE
[CALCITE-3496] Hive dialect and MS SQL dialect support with cube and with rollup

### PR DESCRIPTION
**Pull request by xy2953396112**
Hive and Sql Server dialect support with cube and with rollup.
it should be true in HiveSqlDialect and MssqlDialect.

### CODE REVIEW

**Comment by xy2953396112** [comment]
@hsyuan @danny0405

**Comment by hsyuan** [comment]
Can you squash the commit? Do you think whether we need tests for MS SQL dialect?

**Comment by julianhyde** [comment]
Hive dialect support where? In the JDBC adapter or in the SQL parser? Change the JIRA description and the commit message to fully describe the change, even to someone who does not read the code.

**Comment by xy2953396112** [comment]
> @xy2953396112 Thanks. The change doesn't match with the title. You also changed for MS SQL.

squash the commit and change title.the tests for MS SQL dialect same as Hive. If need to add test,i will add a test for MS SQL dialect.

**Comment by xy2953396112** [comment]
@hsyuan @danny0405 Thanks for you review.

**Comment by xy2953396112** [comment]
@hsyuan is there some problems in this pr?

**Comment by hsyuan** [comment]
Yeah, I commented in the JIRA: https://issues.apache.org/jira/browse/CALCITE-3496

**Comment by xy2953396112** [comment]
@hsyuan Thanks, change the commit messages.

**Comment by xy2953396112** [comment]
Thanks.



---Original---

**Pull request merged**
