### PR TITLE
CALCITE-1412: Use wercker for CI.

### PR DESCRIPTION
**Pull request by F21**
ping @julianhyde @joshelser

### CODE REVIEW

**Comment by joshelser** [comment]
@F21 Is there a way to disable Travis without deleting .travis.yml? This would be easier to go back to running on travis (hypothetically) without trying to find the old file in history.

**Comment by F21** [comment]
@joshelser Good idea. You can disable it in the `Integrations and services` tab in the repo settings. I will restore the file and rebase.

**Comment by F21** [comment]
Ok, `travis.yml` has been restored and the branch has been rebased. To set up wercker, someone with write access to the repo will need to add the app on the wercker website.

**Comment by joshelser** [comment]
> To set up wercker, someone with write access to the repo will need to add the app on the wercker website.

That would have to be a request to the ASF INFRA team. They're the only ones with administrative privileges to access the repositories on Github. Filing a JIRA issue in the INFRA project is one way or you can shoot them an email at infrastructure@apache.org. Sending an email might be best and then you can also cc dev@calcite.

**Comment by F21** [comment]
@joshelser Thanks for the pointers. I've sent a request off to the INFRA team 😄

**Comment by F21** [comment]
The INFRA team just replied that they are unable to set up Wercker because it will need write access to the repo. How was travis originally setup? I can see that it builds under the apache namespace: https://travis-ci.org/apache/calcite/

**Comment by joshelser** [comment]
> The INFRA team just replied that they are unable to set up Wercker because it will need write access to the repo

Ahh that's a bummer. I didn't realize it would need write access. The reasoning is very long-winded if they weren't clear, but, in short, that's definitely not going to happen.

> How was travis originally setup? I can see that it builds under the apache namespace:

Maybe travis doesn't require write access to the repo? Not sure.

**Comment by F21** [comment]
In this case, I think this PR should be closed. Let's try and get ASFBot to build PRs using the ASF jenkins instance and continue the discussion in the relevant JIRAs.

**Pull request closed without merging**
