### PR TITLE
[CALCITE-2366] Add support for ANY_VALUE aggregate function

### PR DESCRIPTION
**Pull request by gparai**
Committers could you please review this PR? More details regarding the mailing list discussions are in the JIRA. Thanks!

### CODE REVIEW

**Comment by amansinha100** [comment]
These planning changes look good.  I was wondering if you have looked into the run-time changes in the Calcite executor for this agg function (for example `MinMaxImplementor`) ?  I am not familiar with that part of Calcite.  Perhaps someone else can offer suggestions there.

**Comment by gparai** [comment]
@amansinha100 thanks for the review. I looked at the Calcite executor but did not completely understand it. It would be great if someone in the community could offer some insights (maybe some documentation or notes). Meanwhile, I will continue exploring it.

**Comment by eolivelli** [comment]
@gparai no real problem from my side, I was just asking, 
I am not an expert of non deterministic functions, I don't know if this may be a problem.

**Comment by gparai** [comment]
@julianhyde thank you so much for reviewing the PR. I have addressed your review comments. Please take a look.

**Pull request closed without merging**
