### PR TITLE
[CALCITE-2442] Cassandra intermittent test failures 

### PR DESCRIPTION
**Pull request by asereda-gs**
1. Wrong parsing of new [JDK version scheme](http://openjdk.java.net/jeps/223) (by calcite and cassandra dependencies like jamm). `10-ea` vs `10.0.2`
2. Cassandra startup timeout on Linux Jenkins CI server. Contrary to github travis CI (the one which validates PRs), it takes about 20s for embedded cassandra to start (still under investigation).
3. Windows OS. [CassandraUnit](https://github.com/jsevellec/cassandra-unit) leaves `.toDelete` folder in maven module folder (`cassandra/`) rather than `target/` where all build and temporary files should be located. Not a failure but annoyance.
4. Explicitly shutdown cassandra cluster (not done by CassandraUnit by default)

### CODE REVIEW

**Comment by michaelmior** [comment]
Doesn't fix things for me. But the failure I'm experiencing (which i think is the same as @julianhyde) is not intermittent and happens consistently. I haven't had any luck fixing it, but I know it happens during startup.

**Comment by michaelmior** [comment]
That said, thanks for this PR and it should still be merged.

**Comment by asereda-gs** [comment]
Can you please describe the error in more details ? Stack trace, environment (OS, JDK, etc.)

**Comment by michaelmior** [comment]
@asereda-gs You can see my commit [here](https://github.com/michaelmior/calcite/commit/57cb98232685bb21c1cb0428512dcf2ed41f7bae). Feel free to just take those changes and apply where needed. I discovered when I couldn't reproduce the issue that it only applies to JDK versions with no dot in them, i.e. "10" instead of "10.0.0"

**Comment by asereda-gs** [comment]
@michaelmior applied your patch to this PR. Thanks!

**Comment by asereda-gs** [comment]
@julianhyde We may be conflating two issues here: 
1) Wrong parsing of new [JDK version scheme](http://openjdk.java.net/jeps/223) (by calcite **and cassandra dependencies**). This is Mike's fix (d1f21de9).
2) Cassandra startup timeout on Linux Jenkins CI server. Contrary to github travis CI (the one which validates PRs), it takes about 20s for embedded cassandra to start. For now we have increased timeout to 30s in CassandraUnit (included in this PR). I will get back to you with more information about high startup times in Jenkins after investigation.

**Comment by michaelmior** [comment]
Agreed that I think this PR and the associated JIRA are conflating two different issues, both relating to fixing problems with CassandraUnit. I'd suggest a rename to clarify.

**Pull request closed without merging**
