### PR TITLE
[CALCITE-2510] Add CHR built-in function (Oracle only)

### PR DESCRIPTION
**Pull request by sergeyT2**

### CODE REVIEW

**Comment by julianhyde** [comment]
A good start - thanks for contributing! Can you please log a JIRA case, and post a link to it here.

Also update the documentation, reference.md.

This function isn't standard SQL. What databases support this? Maybe OracleSqlOperatorTable is a better place for this to live.

**Comment by aai95** [comment]
Hi @julianhyde,
Function renamed in `OracleSqlOperatorTable`. CHR removed from `Parser.jj`. VARCHAR2 removed from `reference.md`.
Please, let me know if any further changes are necessary.

**Comment by chunweilei** [comment]
Can you please move the function to `SqlLibraryOperators` ?

**Comment by michaelmior** [comment]
It would help if you could also resolve the current merge conflicts.

**Comment by chunweilei** [comment]
some fix-up in https://github.com/chunweilei/calcite/commit/77365bb137742c41c791785a251f00f47b8760bc.

**Comment by julianhyde** [comment]
Can someone make a pass to fix code style? E.g. adding a field with two blank lines before, no blank lines after. And indentation.

And move it to the "dialect-specific operators" in the doc.

**Comment by julianhyde** [comment]
Do we need so many overloads in SqlFunctions? I suspect that `chr(long)` would be sufficient.

**Comment by chunweilei** [comment]
> Can someone make a pass to fix code style? E.g. adding a field with two blank lines before, no blank lines after. And indentation. And move it to the "dialect-specific operators" in the doc.

I made some fix-up in https://github.com/chunweilei/calcite/commit/77365bb137742c41c791785a251f00f47b8760bc.

**Comment by chunweilei** [comment]
> Do we need so many overloads in SqlFunctions? I suspect that chr(long) would be sufficient.

Makes sense.

**Comment by hsyuan** [comment]
+1 on @chunweilei 's commit.

**Pull request closed without merging**
