### PR TITLE
[CALCITE-3548] rename ubenchmark/src/main/jmh to ubenchmark/src/jmh/java

### PR DESCRIPTION
**Pull request by amaliujia**
src/jmh/java to make `./gradlew :ubenchmark:jmh` find benchmark
classes to run.

Details in https://issues.apache.org/jira/browse/CALCITE-3548.

### CODE REVIEW

**Comment by amaliujia** [comment]
@vladimirdolzhenko

**Comment by amaliujia** [comment]
Actually seems like this change will make `:ubenmark:jmh` be triggered by `./gradlew check`. Is the original structure intentional to avoid benmarks run by `check`?

If it is intentional, is there a separate command to run benchmarks? 
If it is not intentional, do we want to avoid benchmarks run by `check`?

**Comment by danny0405** [comment]
@vlsi Can you make some help ?

**Comment by vlsi** [comment]
> Actually seems like this change will make :ubenmark:jmh be triggered by ./gradlew check

It does not seem to be the case for me.

> original structure intentional

I think the original structure is just a mistake. It was not intentional

**Comment by vlsi** [comment]
Just in case: Gradle has `--dry-run` option (which has `-m` short form), and it does print the tasks to be executed.

```
$ ./gradlew :ubenchmark:check -m
...
:linq4j:compileJava SKIPPED
:core:compileKotlin SKIPPED
:core:fmppMain SKIPPED
:core:javaCCMain SKIPPED
:core:versionClass SKIPPED
:core:compileJava SKIPPED
:ubenchmark:compileJava SKIPPED
:ubenchmark:processResources SKIPPED
:ubenchmark:classes SKIPPED
:ubenchmark:compileTestJava SKIPPED
:ubenchmark:processTestResources SKIPPED
:ubenchmark:testClasses SKIPPED
:ubenchmark:compileJmhJava SKIPPED
:ubenchmark:processJmhResources SKIPPED
:ubenchmark:jmhClasses SKIPPED
:ubenchmark:checkstyleJmh SKIPPED
:ubenchmark:checkstyleMain SKIPPED
:ubenchmark:checkstyleTest SKIPPED
:ubenchmark:forbiddenApisJmh SKIPPED
:ubenchmark:forbiddenApisMain SKIPPED
:ubenchmark:forbiddenApisTest SKIPPED
:ubenchmark:forbiddenApis SKIPPED
:ubenchmark:spotlessJava SKIPPED
:ubenchmark:spotlessJavaCheck SKIPPED
:ubenchmark:spotlessKotlinGradle SKIPPED
:ubenchmark:spotlessKotlinGradleCheck SKIPPED
:ubenchmark:spotlessCheck SKIPPED
:ubenchmark:test SKIPPED
:ubenchmark:check SKIPPED
```

That is `:jmh` task is not going to be executed when `check` is requested.

**Comment by amaliujia** [comment]
@vlsi thanks for the `dry-run` information (didn't know it but it's indeed handy). Maybe I have mis-read logs before. 

Great then. This PR should make `:ubenchmark:jmh` work without affecting `ubenchmark:check` then.

**Pull request closed without merging**
