### PR TITLE
[CALCITE-2744] RelDecorrelator use wrong output map for LogicalAggregate

### PR DESCRIPTION
**Pull request by danny0405**
decorrelate

### CODE REVIEW

**Comment by danny0405** [comment]
@chunweilei @hsyuan  Can you please review this for PR for me ?

**Comment by vvysotskyi** [comment]
Looks like the same change was done in https://github.com/apache/calcite/pull/1254. @danny0405, is it possible to collaborate with that PR, since it was opened earlier?

**Comment by danny0405** [comment]
> Looks like the same change was done in #1254. @danny0405, is it possible to collaborate with that PR, since it was opened earlier?

I worked this PR based on #1254, and if we make sure this fix is ok, i would close this PR and rebase the logic in #1254 the merge it in.

**Comment by julianhyde** [comment]
Please see my comments in the other PR.

**Comment by danny0405** [comment]
> Please see my comments in the other PR.

Thanks, @julianhyde ,i would like this close this one.

**Pull request closed without merging**
