### PR TITLE
[CALCITE-2289] Enable html5 for Javadoc on JDK 9+

### PR DESCRIPTION
**Pull request by risdenk**
* Add JDK9+ profile to enable -html5 for javadoc
* Add javadoc verification to .travis.yml to match Jenkins build

### CODE REVIEW

**Comment by michaelmior** [comment]
What's the benefit of doing this (serious question)? If we don't have a good reason for doing so, I'd be inclined to wait until we drop JDK 8 support at some point in the future.

**Comment by risdenk** [comment]
@michaelmior valid question. html5 support for javadocs is really nice but does require JDK 9. One benefit of doing this now is we get earlier testing of javadocs against later JDKs with HTML5. Either way I'm not in a rush to merge this.

**Comment by risdenk** [comment]
Looks like this was addressed separately in https://github.com/apache/calcite/commit/9d6899c919113dc58707b2337297205ed1d7194f

**Comment by michaelmior** [comment]
Thanks for cleaning this up @risdenk  :)

**Pull request closed without merging**
