### PR TITLE
[CALCITE-3950] Doc of SqlGroupingFunction contradicts its behavior

### PR DESCRIPTION
**Pull request by jinxing64**

### CODE REVIEW

**Comment by DonnyZone** [comment]
+1 for updating the Javadoc.
How about borrowing some descriptions from SqlServer's doc[1] or Oracle's doc[2]?
[1] https://docs.microsoft.com/en-us/sql/t-sql/functions/grouping-id-transact-sql?view=sql-server-ver15
[2] https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions063.htm

**Comment by jinxing64** [comment]
Sure ~ update soon

**Comment by DonnyZone** [comment]
LGTM

**Comment by jinxing64** [comment]
@DonnyZone Thanks I will re-trigger the CI

**Comment by jinxing64** [comment]
travis-ci keeps failing. It seems the building environment has problem.

**Comment by jinxing64** [comment]
Since @DonnyZone  gives +1 for this change. I will add a LGTM-will-merge-soon tag. Welcome further comments and I will update ASAP before merging.

**Pull request merged**
