### PR TITLE
[CALCITE-2254] Test against IBM Java 8

### PR DESCRIPTION
**Pull request by risdenk**
Builds upon PR #649

### CODE REVIEW

**Comment by risdenk** [comment]
The only real change is `- env: IMAGE=maven:3-ibmjava-8` once CALCITE-2063 is fixed can rebase.

**Comment by F21** [comment]
@risdenk Is this safe to merge?

**Comment by risdenk** [comment]
There were test failures last I looked. I can update this and see if we can merge it or figure out what is left to do.

**Comment by risdenk** [comment]
Planning to close this since haven't followed up with fixing test failures. Jira is still open.

**Pull request closed without merging**
