### PR TITLE
[CALCITE-525] Exception-handling in built-in functions

### PR DESCRIPTION
**Pull request by zhztheplayer**
See [JIRA](https://issues.apache.org/jira/browse/CALCITE-525)

### CODE REVIEW

**Comment by vlsi** [comment]
I don't really see a point to adding public API for this.

So -1 as long as public API (e.g. public interfaces) is added.

**Comment by zhztheplayer** [comment]
> I don't really see a point to adding public API for this.
> 
> So -1 as long as public API (e.g. public interfaces) is added.

Hi @vlsi , 

Could you please explain a bit more about why we don't want a public interface here?

I made the interface public just mainly for cross package accessing. Also, generally saying, developers could write custom ExceptionHandler since it is public.

**Comment by vlsi** [comment]
> Also, generally saying, developers could write custom ExceptionHandler since it is public.

I'm ok if you mark interface/enum with `@Experemental` or `@VisibleForTesting` or with something like that.

Adding public APIs is not something that should be added for each and every reason.


PS. You seem to handle each and every EnumerableCalc, however a single query might have multiple EnumerableCalc instances. Does it really make sense to handle all of them?
What sense `log` action means? What is the result of SQL when exception is logged and/or ignored?

**Comment by zhztheplayer** [comment]
@vlsi Thank you very much for the explanation, I leaved my comments in [JIRA](https://issues.apache.org/jira/browse/CALCITE-525), could you please take a look? Thanks.

**Comment by zhztheplayer** [comment]
I'll close this for now, may reopen in future.

**Pull request closed without merging**
