### PR TITLE
[CALCITE-2419] Use embedded Cassandra for tests

### PR DESCRIPTION
**Pull request by asereda-gs**
Small changes on the top of Mike's PR: #764

### CODE REVIEW

**Comment by michaelmior** [comment]
No need to open a separate PR. There's still a few things to be fixed. Currently the dependency check fails on your branch after the import from `org.apache.cassandra`. I'll probably just ignore that warning since it's only used to fix a bug during testing. It also seems like the `cassandra.yaml` that was added is unnecessary. Tests pass for me without it. Can you confirm in IntelliJ?

**Comment by michaelmior** [comment]
No problem. Can you confirm that the cassandra.yaml isn't needed? Things seem to work fine for me without it and I'd rather not include it if not needed.

**Comment by asereda-gs** [comment]
`cassandra.yaml` **is** required in IntelliJ 2018.2 (jdk10). Otherwise cluster can't initialize properly.

**Comment by michaelmior** [comment]
Okay, no problems here then. Feel free to merge this :) Thanks for the help!

**Comment by asereda-gs** [comment]
Are you OK if these tests are skipped on JDK11 ? Last JDK11 is supported only by Cassandra 4.0+ (which is not released yet). For more details see [CASSANDRA-9608](https://issues.apache.org/jira/browse/CASSANDRA-9608).

**Comment by asereda-gs** [comment]
All tests pass now (JDK11 ignored)

**Comment by michaelmior** [comment]
Great! Thanks again for the help :)

**Pull request closed without merging**
