### PR TITLE
[CALCITE-4884] Provide a new constructor for RelJsonWriter to allow customized JsonBuilder

### PR DESCRIPTION
**Pull request by chunweilei**

### CODE REVIEW

**Comment by chunweilei** [comment]
@xy2953396112 Could you help review the PR?

**Review by NobiGo — APPROVED** [review]

**Comment by xy2953396112** [comment]
ustomized --> customized?

**Comment by xy2953396112** [comment]
LGTM~

**Comment by chunweilei** [comment]
> ustomized --> customized?

Oops. The title is wrong while the commit message is right.

**Pull request merged**
