### PR TITLE
CALCITE-1386 ITEM operator seems to ignore the value type of collection and assign the value to Object

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Observed behavior is described here: https://issues.apache.org/jira/browse/CALCITE-1386

Below is the description of this patch:

* Modify MethodImplementor to cast return value to desired return type when necessary
* Change ItemImplementor to use NullPolicy.ANY since ITEM can still return null even though both operands are not null
* Fix Types.castIfNecessary to handle RecordType as an exceptional case (toClass() doesn't handle RecordType and throws Exception)
* Change Csv tests to test its behavior

Please let me know if I'm encouraged to do additional works. Thanks in advance!

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
For reference, origin issue is from Apache Storm: https://github.com/apache/storm/pull/1714
We would like to support nested Map with type & runtime safety.

With this patch, 1 level access of map and array works without applying CAST to value.
In 2 levels (nested) access of map, if first level of value is null (key not found), it throws NullPointerException at runtime.
I'm now trying to see why this respects that any operands of item can be nullable. Please help me if you have an idea why this happens.

**Comment by HeartSaVioR** [comment]
I had been digging above and found there's no support on nullable AbstractSqlType.
SqlTypeFactoryImpl.createTypeWithNullability() doesn't handle AbstractSqlType overriding its nullability. Is there other way to define SQL type field to nullable?

**Comment by HeartSaVioR** [comment]
Never mind. Map and Array type seems to be missing. Addressed to 44573cc.

**Comment by julianhyde** [comment]
I did a quick review and it all looks good, but can you please add some tests?

**Comment by HeartSaVioR** [comment]
@julianhyde OK. I'll add relevant tests and mention you. Thanks for guiding!

**Comment by julianhyde** [comment]
Even better, add a comment to the jira case.

**Comment by HeartSaVioR** [comment]
Please have a look at `testAccessNestedMapWithANYTypeWithoutCAST`. 

SqlFunctions.eq() only provides two overloaded signatures, (Object, Object) and (BigDecimal, BigDecimal). But there could be another case (Object, BigDecimal) when left operand is Object (type information is not provided) and right operand is primitive type.

Is it better to handle this case to make life easier as well? If you agree I'll handle this from another issue.

**Comment by julianhyde** [comment]
I've seen those problems before - with all the combinations of null and not-null values (e.g. `eq(int, int)`, `eq(Integer, int)`, `eq(int, Integer)`, `eq(Integer, Integer)`). I realized that I couldn't create a method for each combination; I had to solve it with code generation. I think your problem is very similar.

In https://issues.apache.org/jira/browse/CALCITE-1054, I take a radical approach to null handling: check for nulls first, then later assume that the value is not null and can be converted to a primitive. I got quite far - see the PR attached to that case - but never quite got it committed. I still think it's a very worthwhile approach. The same approach could be applied to dynamic typing, I think. Can you take a look at the PR and see whether it would work?

**Comment by julianhyde** [comment]
@HeartSaVioR, In CsvTest.testJson, why did you add a WHERE clause?

**Comment by HeartSaVioR** [comment]
@julianhyde CsvTest.testJson was a quick test fix before adding unit test on core. I'll revert it.

**Comment by HeartSaVioR** [comment]
@julianhyde And yes, I'll take a look at it. Btw, I think we can handle it as separate issue.

**Comment by HeartSaVioR** [comment]
OK. Got it back.

**Comment by julianhyde** [comment]
Yes, let's treat .eq as a separate issue. There's enough in this PR already!

I have a question about `testNestedArrayOutOfBoundAccess`. You go with PostgreSQL's semantics (return null) rather than standard SQL (throw an exception). I'd prefer to go with the standard behavior, and return null only if enabled by a `Conformance` setting. Do you agree?

And by the way, I can't see which code you changed to get rid of the ArrayIndexOutOfBoundsException. What did you change?

Don't worry about CsvTest.testJson. I am making a few edits as I review. I'll change it.

**Comment by HeartSaVioR** [comment]
I'm OK if it can be changed based on preferences.

And actually `arrayItem` is already implemented as not throwing an exception, so if we want to respect SQL standard, we should change that.
```
  public static Object arrayItem(List list, int item) {
    if (item < 1 || item > list.size()) {
      return null;
    }
    return list.get(item - 1);
  }
```

I'm not clear why ArrayIndexOutOfBound happened before patching.

**Comment by julianhyde** [comment]
Ah, it seems that you didn't make `arrayItem` any worse. Let's leave it for now, then. Can you log a JIRA case that the current behavior is wrong?

I just pushed a branch with my fix-ups to your edit, https://github.com/julianhyde/calcite/tree/1386-item. Let me know if my changes are OK; if so I'll squash and commit.

**Comment by HeartSaVioR** [comment]
I'll file an issue for that. Btw, I left comment on your fix. NullPolicy of ITEM should be ANY even if we follow standard SQL.

**Comment by HeartSaVioR** [comment]
Other than it looks great. Thanks for clearing up, @julianhyde.

**Comment by HeartSaVioR** [comment]
Filed https://issues.apache.org/jira/browse/CALCITE-1401.

Btw, if you want to make a whole conversation from JIRA issue because of the rule of Apache Project (historical data should be stored to Apache infra, AFAIK), I'm OK to move on.

**Pull request closed without merging**
