### PR TITLE
[CALCITE-6679] Reduced the number of type checks in VolcanoPlanner

### PR DESCRIPTION
**Pull request by xiaochen-zhou**
Reduced the number of type checks by moving the instanceof check outside the loop, improving performance and code clarity.

### CODE REVIEW

**Comment by mihaibudiu** [comment]
no need to file an issue for such small changes

**Review by NobiGo — APPROVED** [review]

**Review by caicancai — APPROVED** [review]

**Comment by caicancai** [comment]
> no need to file an issue for such small changes

+1

**Comment by zabetak** [comment]
> no need to file an issue for such small changes

@mihaibudiu I don't fully agree with this suggestion. It maybe be OK to skip JIRA for typos, whitespaces etc., but for actual code changes I find it useful to have JIRA ids for the reasons I expressed in https://lists.apache.org/thread/3xx1rdzgnh44ykdm8xlvgn630b60m8vb

**Review by zabetak — COMMENTED** [review]
I guess its fine to merge this change but the benefits are not clear. The code was already readable before and the "perf gain" from moving the check will hardly make any real perf difference.

**Comment by caicancai** [comment]
> I guess its fine to merge this change but the benefits are not clear. The code was already readable before and the "perf gain" from moving the check will hardly make any real perf difference.

Unfortunately, Calcite does not have a benchmark similar to benchmark

**Comment by caicancai** [comment]
> > no need to file an issue for such small changes
> 
> @mihaibudiu I don't fully agree with this suggestion. It maybe be OK to skip JIRA for typos, whitespaces etc., but for actual code changes I find it useful to have JIRA ids for the reasons I expressed in https://lists.apache.org/thread/3xx1rdzgnh44ykdm8xlvgn630b60m8vb

@zabetak I think this part can be updated to the Calcite documentation to facilitate the review of subsequent PRs

**Pull request merged**
