### PR TITLE
[CALCITE-3239] Calc#accept(RexShuttle shuttle) does not update rowType

### PR DESCRIPTION
**Pull request by jinxing64**
In current code, `Calc#accept(RexShuttle shuttle)` keep the original `rowType`, even when the expression list is modified by the shuttle. https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/rel/core/Calc.java#L175 
It might be wrong and a new `rowType` should be derived.

### CODE REVIEW

**Comment by danny0405** [comment]
There is already a issue CALCITE-3165 for the `Project`, do we really need to do this for `CALC` ?

**Comment by jinxing64** [comment]
Well, I'm not sure.
As long as Calcite provides such a method -- `Calc#accept(RexShuttle shuttle)`. It might make sense to make it work properly.

**Comment by jinxing64** [comment]
@danny0405 
Do you think it's

**Comment by danny0405** [comment]
@rubenada What do you think about this patch ?

**Comment by rubenada** [comment]
@jinxing64 @danny0405 I think we should be consistent and have the same behavior in Project and Calc, so if we already identified and fixed this issue on Project, I'm +1 on fixing it on Calc too.

**Comment by jinxing64** [comment]
@rubenada @danny0405 
Thanks a lot for looking into this ~
If it makes sense to fix this issue in `Calc`, could you please leave more comments on this ? and I can keep refine this patch.

**Comment by jinxing64** [comment]
Thanks for approve !
@hsyuan

**Pull request merged**
