### PR TITLE
[CALCITE-3031] Support for correlated ANY/SOME/ALL sub-query

### PR DESCRIPTION
**Pull request by vineetgarg02**
https://issues.apache.org/jira/browse/CALCITE-3031

### CODE REVIEW

**Comment by hsyuan** [comment]
Can you rebase on master?

**Comment by vineetgarg02** [comment]
> Can you rebase on master?

I have rebased and pushed. Thanks for taking a look.

**Comment by hsyuan** [comment]
Can you check the test failure?

**Comment by vineetgarg02** [comment]
> Can you check the test failure?

@hsyuan I am not able to see the test failure locally. Looks like an environmental glitch. I have rebased and pushed to re-trigger the tests.

**Pull request merged**
