### PR TITLE
[CALCITE-5717] Prune Project's input if project has no InputRef and the input has 1 row

### PR DESCRIPTION
**Pull request by libenchao**
…

### CODE REVIEW

**Comment by herunkang2018** [comment]
The improvement looks good to me, I have another question, is there other case that can be pruned beside this PR's case?

**Comment by libenchao** [comment]
@herunkang2018 Thanks for your review. Other cases can be considered in other Jira if there is any in your mind.

**Comment by JiajunBernoulli** [comment]
LGTM

**Review by JiajunBernoulli — APPROVED** [review]

**Comment by libenchao** [comment]
Closing this since this is resolved in https://github.com/apache/calcite/commit/379f41d3be465992328d5659ea62b8355e0399d1

**Pull request closed without merging**
