### PR TITLE
[CALCITE-3265] remove useless code

### PR DESCRIPTION
**Pull request by xy2953396112**
remove useless code in ExpressionTest.

### CODE REVIEW

**Comment by danny0405** [comment]
Thanks @xy2953396112, but this change is too small to form a PR, maybe we can merge this change into another bigger one ~

**Comment by Fokko** [comment]
@danny0405 Maybe we can merge this with https://github.com/apache/calcite/pull/1393

**Comment by Fokko** [comment]
Personally, I don't think a PR can't be too small :-)

**Comment by hsyuan** [comment]
Yes, better to merge them.

**Comment by xy2953396112** [comment]
> Thanks @xy2953396112, but this change is too small to form a PR, maybe we can merge this change into another bigger one ~

How do you think ?

**Comment by xy2953396112** [comment]
@danny0405 How do you think merge them?

**Comment by Fokko** [comment]
I could have cherry-picked the commit into my PR, but I was sleeping (UTC+2).

**Comment by danny0405** [comment]
@Fokko That's okey, just commit your PR.

**Pull request closed without merging**
