### PR TITLE
[CALCITE-5340] Tests should fail when actual and expected XML reference files are not identical

### PR DESCRIPTION
**Pull request by asolimando**

### CODE REVIEW

**Comment by libenchao** [comment]
@asolimando The PR looks great. The only question I got is why `TopDownOptTest` and `RuleMatchVisualizerTest` are not touched in this PR?

**Comment by asolimando** [comment]
> @asolimando The PR looks great. The only question I got is why `TopDownOptTest` and `RuleMatchVisualizerTest` are not touched in this PR?

@libenchao, thanks a lot for catching it! I totally missed `TopDownOptTest`, for `RuleMatchVisualizerTest` I tried to implement the check in its parent class (`RelOptTestBase`) but it proved difficult, I gave up and forgot about that class.

I have covered them both in a new commit, please have another look if you have any spare cycles.

**Comment by libenchao** [comment]
Sorry that I found another one: `SqlPrettyWriterTest`.

**Review by libenchao — APPROVED** [review]
LGTM. @asolimando thanks for driving this, this is very helpful improvement.

**Comment by asolimando** [comment]
> LGTM. @asolimando thanks for driving this, this is very helpful improvement.

Thanks to you, @libenchao, for your reviews and helpful suggestions!

**Pull request merged**
