### PR TITLE
[CALCITE-4260] Support plan explain with dot format

### PR DESCRIPTION
**Pull request by liyafan82**
See https://issues.apache.org/jira/browse/CALCITE-4260

### CODE REVIEW

**Review by hsyuan — APPROVED** [review]
+1

**Comment by hsyuan** [comment]
@liyafan82 Can you rebase to latest master?

**Comment by liyafan82** [comment]
> @liyafan82 Can you rebase to latest master?

Rebased. Thanks for your attention. @hsyuan

**Review by chunweilei — COMMENTED** [review]
LGTM

**Pull request merged**
