### PR TITLE
[CALCITE-1179] Extend list of time units and time unit ranges for CALCITE-1177

### PR DESCRIPTION
**Pull request by vkorukanti**

### CODE REVIEW

**Comment by vkorukanti** [comment]
@julianhyde Could you please review this PR?

**Comment by vkorukanti** [comment]
Merged as 26a6458903cd13d2a541b59042d178e8177705a9

**Comment by julianhyde** [comment]
Wasn't there a pull request for CALCITE-1177 also? If so, I can't find it anymore. We can't commit CALCITE-1177 until there is a new Avatica release so it's important that pull request stays open.

**Comment by vkorukanti** [comment]
There is no PR for CALCITE-1177 yet. The changes I referred in the JIRA are in my repo: https://github.com/vkorukanti/calcite/commits/CALCITE-1177. I will submit a PR once we have new Avatica release.

**Comment by julianhyde** [comment]
Ah, you're right. I noticed your CALCITE-1177 branch when I was committing CALCITE-1179. I was mistaken that there was a PR for it.

**Pull request closed without merging**
