### PR TITLE
[CALCITE-6131] There are duplicate sample tests in SqlTypeUtilTest

### PR DESCRIPTION
**Pull request by caicancai**
https://issues.apache.org/jira/browse/CALCITE-6131

### CODE REVIEW

**Comment by caicancai** [comment]
cc @JiajunBernoulli

**Review by mihaibudiu — APPROVED** [review]

**Comment by JiajunBernoulli** [comment]
@caicancai  Please rebase main again.

**Comment by caicancai** [comment]
> @caicancai Please rebase main again.

ok, there was no such problem yesterday. I will git rebase later

**Comment by caicancai** [comment]
@mihaibudiu @JiajunBernoulli It seems that the cli has not happened, but I don’t know why this happens. It seems that similar situations have happened before.

**Comment by mihaibudiu** [comment]
This is a very strange failure in CI.

**Comment by caicancai** [comment]
I'll try it in my local Windows environment and see if it comes up

**Comment by caicancai** [comment]
cli passed, which was pretty amazing, and I didn't reproduce it locally

**Comment by JiajunBernoulli** [comment]
> cli passed, which was pretty amazing, and I didn't reproduce it locally

Yes, failure is not your responsibility.

The issue is https://issues.apache.org/jira/browse/CALCITE-4824

I just ran again to make it pass.

**Comment by JiajunBernoulli** [comment]
Close #3544

**Pull request merged**
