### PR TITLE
[CALCITE-4906] Wrong result for scalar subquery from empty input

### PR DESCRIPTION
**Pull request by alex-plekhanov**

### CODE REVIEW

**Review by NobiGo — APPROVED** [review]
LGTM

**Comment by alex-plekhanov** [comment]
@NobiGo can you please advise my next steps? What additionally should I do for this pull request to be merged?

**Comment by amaliujia** [comment]
LGTM

**Comment by amaliujia** [comment]
@alex-plekhanov 

Can you squash your commits into one before I merge this fix to 1.29.0? 

You can find some guidance from here: https://calcite.apache.org/develop/#contributing

**Review by amaliujia — APPROVED** [review]

**Pull request merged**
