### PR TITLE
[CALCITE-6442] Validator rejects FILTER in OVER windows

### PR DESCRIPTION
**Pull request by mihaibudiu**
As discussed in the JIRA, this seems to be a documentation bug

### CODE REVIEW

**Comment by mihaibudiu** [comment]
If you were looking for an easy-to-review PR, this is it. It just removes two lines from the documentation.

**Comment by mihaibudiu** [comment]
https://issues.apache.org/jira/browse/CALCITE-6442

**Review by YiwenWu — APPROVED** [review]
LGTM

**Comment by mihaibudiu** [comment]
As suggested by @julianhyde, I have added a negative test case to the SqlValidatorTest.
I have also squashed the commit, since this is such a small PR.

**Pull request merged**
