### PR TITLE
[CALCITE-2004] Push join predicate down into inner relation for lateral join

### PR DESCRIPTION
**Pull request by hsyuan**
Before this patch, the join predicate was put on top of LogicalCorrelate, which
is wrong plan and may cause wrong result for left outer lateral join.

JIRA: https://issues.apache.org/jira/browse/CALCITE-2004

This PR Also resolves JIRA: https://issues.apache.org/jira/browse/CALCITE-2893

### CODE REVIEW

**Comment by chunweilei** [comment]
It seems that some tests failed.

**Comment by hsyuan** [comment]
Yup, because of the blocking issue: https://issues.apache.org/jira/browse/CALCITE-2903

**Comment by julianhyde** [comment]
@hsyuan 2903 is fixed now. Can you rebase, if necessary? I'll review when the tests pass.

**Comment by hsyuan** [comment]
OK, will do

**Comment by hsyuan** [comment]
@julianhyde Rebased on master and tests passed.

**Pull request merged**
