### PR TITLE
[CALCITE-1297] RelBuilder does not translate identity projects even if they rename fields

### PR DESCRIPTION
**Pull request by wuchong**
Calcite's RelBuilder does not translate identity projects even if they rename fields

### CODE REVIEW

**Comment by julianhyde** [comment]
As discussed in https://issues.apache.org/jira/browse/CALCITE-1297, this patch does not give the right behavior. After providing an identity project that renames fields, RelBuilder should not create an identity project, but for the purposes of the {{RelBuilder.field}} methods the field should have the new name. Plus, the patch needs to add test cases.

**Comment by wuchong** [comment]
Hi @julianhyde , I have updated this PR. Can you have a look again? 

Additionally, I'm confused that why `Frame.right` is a List with only one Pair in it all the time ?

**Comment by julianhyde** [comment]
A join has two named inputs, and the output is the concatenation of the fields from the left with the fields from the right. In this case, Frame.right would have two elements.

**Comment by wuchong** [comment]
Oh, I see. So it looks like that my code still have some problems.

**Comment by julianhyde** [comment]
I've taken your patch a bit further in my branch https://github.com/julianhyde/calcite/tree/1297-rel-builder. It now deals with Aggregate, and I think Join too. So I think it's all good. If the tests pass I'm going to commit.

**Pull request closed without merging**
