### PR TITLE
[CALCITE-6454] Implement array comparison operators

### PR DESCRIPTION
**Pull request by normanj-bitquill**
* <, <=, >, >= now work for arrays and rows
* Can also sort arrays and rows
* Comparison is performed along corresponding indexes
* Longer arrays are considered greater
* null is considered greater than anything
* Cannot change whether nulls are first or last

### CODE REVIEW

**Review by mihaibudiu — COMMENTED** [review]
the natural question is whether this works for other recursive types, such as `int array array`...

**Comment by normanj-bitquill** [comment]
> the natural question is whether this works for other recursive types, such as `int array array`...

@mihaibudiu I'm not sure. This PR currently handles arrays and rows. The arrays and rows can contain scalar values as well as arrays and rows.

Do you have any examples of simple queries that could generate other types? I can generate an array in a query with `SELECT array[1, 2];` and a row with `SELECT row(1, 2);`

**Comment by NobiGo** [comment]
@normanj-bitquill

1) I find different data source has different behaviour about NULL value:

```
spark-sql (default)> select array(1,2)>array(1,null);
true
Time taken: 0.192 seconds, Fetched 1 row(s)
spark-sql (default)> select array(1,2)<array(1,null);
false
Time taken: 0.127 seconds, Fetched 1 row(s)
```
But this maybe another issue to resolve it.

2) Please add the code annotation before the test to make the test more clearly. Others good to me .

**Comment by mihaibudiu** [comment]
> Do you have any examples of simple queries that could generate other types? I can generate an array in a query with `SELECT array[1, 2];` and a row with `SELECT row(1, 2);`

There are some examples in SqlOperatorTest.java, for instance nested arrays: https://github.com/apache/calcite/blob/374091b0a7c24e61a5850e763c20587ff79e04ac/testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java#L7248

**Comment by normanj-bitquill** [comment]
@mihaibudiu I have fixed an issue with comparing rows and added tests with nesting (arrays in arrays, rows in arrays, etc).

**Comment by normanj-bitquill** [comment]
> @normanj-bitquill
> 
> 1. I find different data source has different behaviour about NULL value:
> 
> ```
> spark-sql (default)> select array(1,2)>array(1,null);
> true
> Time taken: 0.192 seconds, Fetched 1 row(s)
> spark-sql (default)> select array(1,2)<array(1,null);
> false
> Time taken: 0.127 seconds, Fetched 1 row(s)
> ```
> 
> But this maybe another issue to resolve it.
> 
> 2. Please add the code annotation before the test to clarify the test. Other good to me.

1. I don't see any obvious way to support specifying the null order. It might help to consider how it should be configured. When building a Spark engine using Calcite, what would the ideal way of specifying whether NULLs should be first or last in array comparisons?

2. I'm not sure what you mean. I added a comment before the tests to say what they are for.

**Review by mihaibudiu — APPROVED** [review]

**Pull request merged**
