### PR TITLE
[MINOR]  Better message when no corresponding example

### PR DESCRIPTION
**Pull request by caicancai**
example1, no example 1

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]
This isn't really a typo, but the fix is fine

**Comment by JiajunBernoulli** [comment]
1. The first letter should be capitalized.
2. Message is not accurate enough: We should use `Better message when ....`.

**Comment by caicancai** [comment]
> 1. The first letter should be capitalized.
> 2. Message is not accurate enough: We should use `Better message when ....`.

So do I need to modify the commit message?

**Comment by JiajunBernoulli** [comment]
> > 1. The first letter should be capitalized.
> > 2. Message is not accurate enough: We should use `Better message when ....`.
> 
> So do I need to modify the commit message?

Yes, remember to rebase main.

**Comment by caicancai** [comment]
I finally learned git rebase, thank you all

**Pull request merged**
