### PR TITLE
Avatica compatibility kit (TCK)

### PR DESCRIPTION
**Pull request by joshelser**
Lots of docs in both a new README and on the website.

@julianhyde et al, would love your opinions as always.

### CODE REVIEW

**Comment by julianhyde** [comment]
I think you should rename hsqldb-server. It happens to use hsqldb, but it would serve its purpose if it used a different database. We don't want people thinking that we intend this to be a good, fully featured, server for hsqldb. That is not its purpose.

The doc doesn't define TCK directly enough. The goal is that if you have implemented an Avatica provider, the TCK will try to kick holes in it, and help you improve the quality of your server faster.

I know I've said it before, but the doc could be more direct. Use active voice, not passive. Present tense, not future. And it's a bit too apologetic about missing functionality.

Why do we need do bundle hsqldb?

**Comment by joshelser** [comment]
> I think you should rename hsqldb-server. It happens to use hsqldb, but it would serve its purpose if it used a different database

Good point. Maybe something like standalone-server? The original point was that it would create a "runnable" jar.

> The doc doesn't define TCK directly enough. The goal is that if you have implemented an Avatica provider, the TCK will try to kick holes in it, and help you improve the quality of your server faster.

Ok, I'll reread what I put on the website with this in mind and see what else I can come up with.

> Why do we need do bundle hsqldb?

Not sure which direction you're coming from with this. If it's from a "why hsqldb?": it could be any database like you say. Or, if it from a "why bundle it?": the intent was to have a standalone artifact that is always available for a release to run Avatica against. If someone files a bug against 1.8.0 and says a 1.8.0 client doesn't work with a 1.6.0 server, I want to be able to easily launch an instance of Avatica 1.6.0 server without having to worry about the integration with some other system (e.g. Phoenix, Drill, etc). Ultimately, we can own it and make it as simple as possible.

**Comment by julianhyde** [comment]
I have no problem with the choice of hsqldb; in fact, I use hsqldb as the basis of sqlline's test suite, for very similar reasons.

It's the "bundling" I am concerned about. Judging by the LICENSE file you are including it in the distribution. Why is this necessary? The TCK is a development-time tool, so you don't need to bundle the binaries that it needs.

**Comment by joshelser** [comment]
> It's the "bundling" I am concerned about. Judging by the LICENSE file you are including it in the distribution. Why is this necessary?

Yes, there is a shaded jar in which HSQLDB is included in. This goes to the 2nd point -- I do not want to make starting a server for testing any harder than it needs to be. Thankfully, HSQLDB is BSD licensed which makes it simple for us to include it and, to the first point, agnostic to the user/dev.

> The TCK is a development-time tool, so you don't need to bundle the binaries that it needs.

IMO, it's necessary because if we make it harder to run, no one will run it. I feel that even now, having to start a server for each version you want to test now is a wart. Having a single JAR file that can be referenced to run a server was an trivial first step to make running this framework easier (lets us punt on bootstrapping all of the necessary servers for the time-being -- long term, I can see a project which fully automates the TCK).

**Pull request closed without merging**
