### PR TITLE
[CALCITE-4177] Throw exception when deserialize SqlOperator, do…

### PR DESCRIPTION
**Pull request by xy2953396112**
… not return null. (Xzh & Wang Yanlin)
CALCITE-4177

### CODE REVIEW

**Comment by xy2953396112** [comment]
@Julian Hyde @yanlin-Lynn @Stamatis Zampetakis
Please help review this pr when you have time.

**Comment by NobiGo** [comment]
@xy2953396112  Please modify the PR commit info about "Throw exception when deserialize SqlOperator fails"  maybe   " "Throw exception when deserialize SqlOperator" is better?

**Comment by xy2953396112** [comment]
> @xy2953396112 Please modify the PR commit info about "Throw exception when deserialize SqlOperator fails" maybe " "Throw exception when deserialize SqlOperator" is better?

thanks for review, update the commit message.

**Review by hsyuan — APPROVED** [review]
LGTM

**Pull request closed without merging**
