### PR TITLE
[CALCITE-5859] Compile-time evaluation of LEFT(NULL, n) should not throw RuntimeException

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Review by chunweilei — APPROVED** [review]
LGTM

**Comment by mihaibudiu** [comment]
Can this fix for a crash be merged?

**Comment by asolimando** [comment]
@mihaibudiu, the patch LGTM, but maybe we can update the title of the Jira ticket (and associated the commit message) along the line of "Compile-time evaluation of LEFT(NULL, n) should not throw RuntimeException"? WDYT?

**Comment by mihaibudiu** [comment]
@asolimando updated the issue name in all places

**Review by asolimando — APPROVED** [review]
Thanks @mihaibudiu for the change, LGTM, will merge 24h from now if there are no objections

**Pull request merged**
