### PR TITLE
[CALCITE-3980] Improvement for creating RedisTable

### PR DESCRIPTION
**Pull request by neoremind**
https://issues.apache.org/jira/browse/CALCITE-3980

### CODE REVIEW

**Comment by DonnyZone** [comment]
LGTM!
cc @XuQianJin-Stars

**Comment by XuQianJin-Stars** [comment]
LGTM +1

**Comment by DonnyZone** [comment]
@neoremind could you please modify the commit message following the document? Thanks!

**Comment by neoremind** [comment]
@DonnyZone Sure, done. Would you help to check? Many thanks. Also thanks Forward to look into this 😄

**Pull request closed without merging**
