### PR TITLE
[CALCITE-2658] Add ExchangeRemoveConstantKeysRule that removes consta…

### PR DESCRIPTION
**Pull request by chunweilei**
…nt keys from Exchange or SortExchange

### CODE REVIEW

**Comment by risdenk** [comment]
@chunweilei Squash commits?

**Comment by chunweilei** [comment]
@risdenk Done. Thank you for reviewing it.

**Comment by chunweilei** [comment]
> @chunweilei looks like there are conflicts?

@risdenk Resolved.

**Comment by chunweilei** [comment]
Hi, @risdenk @asereda-gs ,  Any comment about this PR?

**Comment by chunweilei** [comment]
Some comment can be found in https://issues.apache.org/jira/browse/CALCITE-2658

**Comment by chunweilei** [comment]
@hsyuan I have rebased on master. Thank you very much.

**Comment by hsyuan** [comment]
You have to resolve conflicts.

**Comment by chunweilei** [comment]
@hsyuan Resolved.

**Pull request merged**
