### PR TITLE
[CALCITE-3738] Missing order by logical plan for insert statement

### PR DESCRIPTION
**Pull request by pengzhiwei2018**

### CODE REVIEW

**Comment by amaliujia** [comment]
LGTM thanks!

**Comment by amaliujia** [comment]
@hsuanyi that's an interesting perspective. Will the ordering depends on sinks? For example, insert into a log file which will preserve the order (assume order by timestamp), but some DB might not. If so it's still better to keep the logical sort rel there and leave engines to figure it out?

**Comment by hsyuan** [comment]
You are tagging wrong person. :)
Perhaps. A relation is a bag (multi-set), which is un-ordered. This is the foundation of relational algebra.
When you insert into a log file, it just happens to be sorted on disk. But when you read it out, order is not guaranteed unless you specify order-by. 
https://en.wikipedia.org/wiki/Relation_(database)

**Comment by amaliujia** [comment]
oops!

Agreed with the relation algebra (table by default does not have an ordering)

I was thinking the use case of writing to a log file which preserve the order. And then the log file will be consumed by non sql case: e.g. python scripts which expects the order as the log file is generated from a ORDER BY query.

**Comment by hsyuan** [comment]
Then the script should add a ORDER-BY clause in the query, otherwise ordering is not guaranteed.

**Comment by amaliujia** [comment]
That wasn't the use case I was thinking of but I got what you meant. So basically you think python script should sort the data rather than relying on a non-guaranteed contract of the ordering.


It sounds make sense to me.

**Comment by vlsi** [comment]
Even though it does not guarantee that the order will be preserved, it makes sense to keep the sorting.

For instance, it would enable to cluder rows appropriately, so later selects would be faster (less physical IO).

Oracle DB explicitly mentions that case in the documentation: https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_7002.htm#SQLRF54628

**Comment by amaliujia** [comment]
The Oracle's documentation is a good reference.

+1 on this PR.

**Pull request merged**
