### PR TITLE
[CALCITE-6184] Add checkNullTest on SqlOperatorTest

### PR DESCRIPTION
**Pull request by caicancai**
https://issues.apache.org/jira/browse/CALCITE-6184

### CODE REVIEW

**Comment by caicancai** [comment]
https://github.com/apache/calcite/pull/3608

**Comment by macroguo-ghy** [comment]
Have you ever used scripts or something else to find all tests that do not contain `checkNull`?

**Comment by caicancai** [comment]
> Have you ever used scripts or something else to find all tests that do not contain `checkNull`?

Yes, but it is mainly done manually, and it is explained in jira that some functions do not need to add checknull, such as map and array.

**Review by macroguo-ghy — APPROVED** [review]
LGTM. I will merge this PR over the weekend if no other comments.

**Review by XuQianJin-Stars — APPROVED** [review]

**Pull request merged**
