### PR TITLE
[CALCITE-4172] Expand columnar identifiers before resolution (James Starr)

### PR DESCRIPTION
**Pull request by jamesstarr**

### CODE REVIEW

**Comment by jamesstarr** [comment]
If there are no objections, could I get this merged.

**Comment by danny0405** [comment]
> If there are no objections, could I get this merged.

I think we could, would merge it soon ~

**Comment by jamesstarr** [comment]
@danny0405 is this going to get merged?

**Comment by danny0405** [comment]
@jamesstarr Already merged in https://github.com/apache/calcite/commit/468b111b3cae44efd31e60c4bafe0018c8821e9a

**Comment by jamesstarr** [comment]
Ah, Thank you.  I will be sure to check main next time.

**Pull request closed without merging**
