### PR TITLE
[CALCITE-6234] Add tests on SqlOperatorTest for to_char function

### PR DESCRIPTION
**Pull request by caicancai**
https://issues.apache.org/jira/browse/CALCITE-6234

### CODE REVIEW

**Comment by caicancai** [comment]
I have to admit that this is a problem left by my previous PR, and I'm sorry for that.

**Comment by rubenada** [comment]
> I have to admit that this is a problem left by my previous PR, and I'm sorry for that.

What previous PR? Is [CALCITE-6234](https://issues.apache.org/jira/browse/CALCITE-6234) related to another Jira? In which case, could you please link both?

**Comment by caicancai** [comment]
> > I have to admit that this is a problem left by my previous PR, and I'm sorry for that.
> 
> What previous PR? Is [CALCITE-6234](https://issues.apache.org/jira/browse/CALCITE-6234) related to another Jira? In which case, could you please link both?

Thank you for your reply https://github.com/apache/calcite/pull/3642

**Comment by caicancai** [comment]
At that time I forgot to add tests in sqloperatortest

**Comment by rubenada** [comment]
Thanks for the clarification @caicancai about the related PR

I'm a bit confused, because the Jira title & description (and the PR title and commit message) talk about `format_date` function, but in fact the new tests involve `to_char`. May I suggest as commit message (and Jira title and PR title) something along the lines:
`[CALCITE-6234] Add tests on SqlOperatorTest for to_char function` ?

**Comment by caicancai** [comment]
> Thanks for the clarification @caicancai about the related PR
> 
> I'm a bit confused, because the Jira title & description (and the PR title and commit message) talk about `format_date` function, but in fact the new tests involve `to_char`. May I suggest as commit message (and Jira title and PR title) something along the lines: `[CALCITE-6234] Add tests on SqlOperatorTest for to_char function` ?

OK, thanks. Please forgive my unclear description

**Comment by rubenada** [comment]
@caicancai  could you please also amend the commit message to have the same?

**Comment by caicancai** [comment]
> @caicancai could you please also amend the commit message to have the same?

done.

**Pull request merged**
