### PR TITLE
[CALCITE-6428] Update adapter.md

### PR DESCRIPTION
**Pull request by thadguidry**
- fixes typo for time window example

### CODE REVIEW

**Review by NobiGo — APPROVED** [review]
LGTM

**Comment by mihaibudiu** [comment]
Such small fixes don't need a JIRA issue.

**Comment by mihaibudiu** [comment]
Dang, I merged again too soon. I will undo this.

**Comment by mihaibudiu** [comment]
Please submit another PR where the commit message and the PR title match exactly the JIRA title.

**Comment by mihaibudiu** [comment]
Actually, let me do it myself, it's not that hard.

**Pull request merged**
