### PR TITLE
[Minor] Refactor Matcher class with remove removePartialMatch

### PR DESCRIPTION
**Pull request by xuzifu666**
removePartialMatch is useless in Mather，and avoid be used by other function remove it

### CODE REVIEW

**Comment by xuzifu666** [comment]
@bchapuis have a review please, thanks

**Comment by bchapuis** [comment]
Sorry, I'm not a commiter to Apache Calcite and lack context to form an opinion on this change.

**Comment by xuzifu666** [comment]
@danny0405 Hi, teacher danny, the api is not used in Calcite，and want to remove it to aviod other developers use it.

> Sorry, I'm not a commiter to Apache Calcite and lack context to form an opinion on this change.

get

**Comment by xuzifu666** [comment]
> Sorry, I'm not a commiter to Apache Calcite and lack context to form an opinion on this change.

get

**Comment by xuzifu666** [comment]
@danny0405 Teacher Chan,  the api is not used in Calcite, want to refactor it throght remove it for other developers not use the api，thanks

**Comment by JiajunBernoulli** [comment]
It is public method, maybe some uses use it. We should not remove it unless there is a better method for users.

**Pull request closed without merging**
