### PR TITLE
Calcite this is a very strange mistake

### PR DESCRIPTION
**Pull request by love1693294577**
0: jdbc:calcite:model=/root/calcite/apache-ca> select sum("xxx") as  a from "xxx";
java.lang.NumberFormatException: For input string: "13485468068"
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseInt(ByteFragmentUtils.java:61)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getInt(ClickHouseResultSet.java:342)
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:623)
	at org.apache.commons.dbcp2.DelegatingResultSet.getInt(DelegatingResultSet.java:623)
	at Baz$1$1.apply(Unknown Source)
	at org.apache.calcite.runtime.ResultSetEnumerable$ResultSetEnumerator.current(ResultSetEnumerable.java:365)
	at org.apache.calcite.linq4j.Linq4j$EnumeratorIterator.next(Linq4j.java:683)
	at org.apache.calcite.avatica.util.IteratorCursor.next(IteratorCursor.java:46)
	at org.apache.calcite.avatica.AvaticaResultSet.next(AvaticaResultSet.java:217)
	at sqlline.BufferedRows.nextList(BufferedRows.java:110)
	at sqlline.BufferedRows.<init>(BufferedRows.java:52)
	at sqlline.SqlLine.print(SqlLine.java:1640)
	at sqlline.Commands.executeSingleQuery(Commands.java:1017)
	at sqlline.Commands.execute(Commands.java:957)
	at sqlline.Commands.sql(Commands.java:921)
	at sqlline.SqlLine.dispatch(SqlLine.java:717)
	at sqlline.SqlLine.begin(SqlLine.java:536)
	at sqlline.SqlLine.start(SqlLine.java:266)
	at sqlline.SqlLine.main(SqlLine.java:205)

The data I got is integer, and I am getting an error.

However, this is not an error.

select "xx","xx",sum("xx") as xx from "xx"  group by "xx","xxx" limit 1;

### CODE REVIEW

**Comment by danny0405** [comment]
Thanks @love1693294577 for reporting this, you may also need to fire a JIRA issue to trace this problem, the JIRA issues is a better choice for tracing discussions.

**Comment by love1693294577** [comment]
> the JIRA issues is a better choice for tracing discussions

How to submit, I have not found it for a long time.

**Comment by danny0405** [comment]
@love1693294577  Please see this page https://issues.apache.org/jira/projects/CALCITE/issues

**Comment by F21** [comment]
@love1693294577 I am going to go ahead and close this PR, because you are trying to merge my `test-site` branch in to master. Since I am testing some stuff on the `test-site` branch, travis and other CI will be triggered when I push to that branch. 

Please open an issue at https://issues.apache.org/jira/projects/CALCITE/issues as @danny0405 suggested.

If you have any other questions please subscribe to our mailing list at dev@calcite.apache.org to post.

**Pull request closed without merging**
