### PR TITLE
[CALCITE-3126] Remove deprecated SemiJoin usage completely

### PR DESCRIPTION
**Pull request by danny0405**

### CODE REVIEW

**Comment by amitvc** [comment]
@danny0405 What is replacement for EnumerableSemiJoin.java ?

**Comment by danny0405** [comment]
EnumerableNestedLoopJoin

**Comment by amitvc** [comment]
@danny0405 Thank you.

**Comment by rubenada** [comment]
As @danny0405 said, EnumerableNestedLoopJoin can support SemiJoin with any type of join condition.
In case of SemiJoin with equi-join condition, EnumerableHashJoin can be used as a replacement too.

**Comment by eolivelli** [comment]
@amitvc Please take a look, this change will help you in the upgrade to 1.21

**Comment by danny0405** [comment]
@zabetak Maybe we should put the change and equivalent plan to the 1.21 release nodes or breaking changes, this would help the user for the upgrade.

**Pull request merged**
