### PR TITLE
[CALCITE-2855] Make RelOptCluster constructor public

### PR DESCRIPTION
**Pull request by godfreyhe**
Expose RelOptCluster Constructor outside package to allow override.

### CODE REVIEW

**Comment by zabetak** [comment]
The author of the PR must be the same with the one who made the commits otherwise it will not be accepted.

**Comment by godfreyhe** [comment]
Thanks for your reminding, I will change commit message ASAP.

**Comment by michaelmior** [comment]
@godfreyhe In the future, no need to create a new PR. Just change the commit and force push to the same branch and the PR will be updated.

**Comment by godfreyhe** [comment]
thanks for your suggestion @michaelmior

**Pull request closed without merging**
