### PR TITLE
[CALCITE-2301] Remove the 10-second-timeout restriction in ResultSetEnumerable

### PR DESCRIPTION
**Pull request by ddmbr**
It's not a good idea to have the magic number here. Also, databases may not get back within 10 second for various reasons (e.g., in the case of JDBC schema).

### CODE REVIEW

**Comment by julianhyde** [comment]
Please log a JIRA case for this. Let's discuss. This probably needs to be configurable.

**Comment by ddmbr** [comment]
@julianhyde OK! Will do.

**Comment by ddmbr** [comment]
@julianhyde Done. I have tried to create a JIRA case before, and so please let me know whether it looks good to you: https://issues.apache.org/jira/browse/CALCITE-2301

**Comment by vlsi** [comment]
Closing in favour of https://github.com/apache/calcite/pull/995

**Pull request closed without merging**
