### PR TITLE
Remove unused parameter from MapConstructor in Parser.jj

### PR DESCRIPTION
**Pull request by onlyotdn**

### CODE REVIEW

**Comment by chucheng92** [comment]
hi @onlyotdn, thanks for reporting this. I believe it may be related to [CALCITE-5918](https://issues.apache.org/jira/browse/CALCITE-5918) that issue refactored this part of the parser logic. It looks good to me.

**Comment by onlyotdn** [comment]
> how about change the commit to "Remove unused parameter from MapConstructor in Parser.jj" ?

**Comment by onlyotdn** [comment]
> how about change the commit to "Remove unused parameter from MapConstructor in Parser.jj" ?

Thank you for helping review code. I think your suggestion is more suitable. I have changed it. In addition, because only the commit message was changed, I used git push --force. If there are inappropriate places, I will help to point out that I will correct it in the future. (I accidentally closed PR just now, please ignore it)

**Comment by JiajunBernoulli** [comment]
LGTM

**Review by JiajunBernoulli — APPROVED** [review]

**Review by macroguo-ghy — APPROVED** [review]

**Review by chucheng92 — APPROVED** [review]
LGTM. thanks for your patch! merging now ...

**Pull request merged**
