### PR TITLE
CALCITE-2112: Add Maven wrapper for Calcite

### PR DESCRIPTION
**Pull request by rdsr**
`./mvnw clean install -DskipTests` passes on my Mac

### CODE REVIEW

**Comment by julianhyde** [comment]
Per discussion at https://issues.apache.org/jira/browse/CALCITE-2112 we're not going to merge this PR at this time.

**Comment by michaelmior** [comment]
@rdsr If you wouldn't mind closing this, it would be helpful in keeping track of issues/PRs that have yet to be addressed. Thanks!

**Comment by rdsr** [comment]
Makes sense Michael. I'll close it.

**Comment by michaelmior** [comment]
Thanks!

**Pull request closed without merging**
