### PR TITLE
Correct typos in Gradle file comments

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]
Technically this is not javadoc

**Comment by caicancai** [comment]
> Technically this is not javadoc

Typo in comment？

**Comment by caicancai** [comment]
> Technically this is not javadoc

How about ‘Correct typos in Gradle file comments’

**Comment by mihaibudiu** [comment]
Better

**Comment by NobiGo** [comment]
@caicancai @mihaibudiu Because there have been several instances where we have not reached a consensus on Java comments, in order to improve this situation, I do some research about java comment. How about we distinguish Java comments into two types, namely 'Java doc comments' and 'Java comments'(Don't include the Java doc comments).

- Doc comments describe Java classes, interfaces, constructors, methods, and fields. Each doc comment is set inside the comment delimiters /**...*/, with one comment per class, interface, or member. This comment should appear just before the declaration.
- Others include (block, single-line, trailing, and end-of-line). We collectively refer to it as Java comments.

1) https://stackoverflow.com/questions/3607641/javadoc-comments-vs-block-comments
2) https://www.oracle.com/java/technologies/javase/codeconventions-comments.html#385

**Review by NobiGo — APPROVED** [review]

**Comment by mihaibudiu** [comment]
This was not a Java file

**Comment by caicancai** [comment]
> @caicancai @mihaibudiu Because there have been several instances where we have not reached a consensus on Java comments, in order to improve this situation, I do some research about java comment. How about we distinguish Java comments into two types, namely 'Java doc comments' and 'Java comments'(Don't include the Java doc comments).
> 
> * Doc comments describe Java classes, interfaces, constructors, methods, and fields. Each doc comment is set inside the comment delimiters /**...*/, with one comment per class, interface, or member. This comment should appear just before the declaration.
> * Others include (block, single-line, trailing, and end-of-line). We collectively refer to it as Java comments.
> 
> 1. https://stackoverflow.com/questions/3607641/javadoc-comments-vs-block-comments
> 2. https://www.oracle.com/java/technologies/javase/codeconventions-comments.html#385

Thank you, we can follow this later, but this PR is only to correct typos

**Comment by caicancai** [comment]
@mihaibudiu @NobiGo Good to merge?

**Pull request merged**
