### PR TITLE
[CALCITE-3184] Add the new logo to the website

### PR DESCRIPTION
**Pull request by zabetak**
1. Add svg/png versions of the new logo.
2. Retain the old-logo for other usages.
3. Improve site's layout for better presentation and resizing.
4. Unify site's mobile and desktop navigation layouts.
5. Compress site/img/*.png using pngquant.

### CODE REVIEW

**Comment by danny0405** [comment]
Nice job, look much pretty !

**Comment by vlsi** [comment]
@zabetak , did you optimize the png?
`pngquant` reduces the image from 32K to 14K. Of course it is not megabytes, but it is something that comes for free, so why don't we just use optimized pngs?

**Comment by zabetak** [comment]
Thanks for your kind words and the comments @F21, @danny0405, @vlsi.

@vlsi I did some compression but not with the tool you mentioned. What is used now in the website is the svg version so in principle the png logos could be deleted.

**Comment by danny0405** [comment]
Thanks so much @zabetak ! It seems that there is some pixel problem for the logo on my Mac OS + Chrome. Even if i full screen the browser.

**Comment by zabetak** [comment]
@danny0405 thanks for the feedback Danny! Can you share a screenshot with the problem? I'm no Mac + Chrome and it seems fine!

**Pull request closed without merging**
