### PR TITLE
[CALCITE-2264] User defined function should not be pushed to jdbc subschema.

### PR DESCRIPTION
**Pull request by ptrbojko**
Adding test with a function to check whether projection with such function
is not pushed to jdbc.

### CODE REVIEW

**Comment by julianhyde** [comment]
Can you explain the motivation for this test?

"Join" is a misleading name for a function in the SQL world.

Need newline at the end of the .iq file.

Remove "[CALCITE-2088]" from the commit comment. That issue was closed in a previous release. We don't need a JIRA case for a minor commit.

**Comment by ptrbojko** [comment]
HEAD~1 have had a bug in which some user defined functions in json was pushed down to jdbc schema. HEAD at the time of pull creation worked for this pretty ok. So I thought that shipping such test (with custom function in projection of select from jdbc table) would assure that this bug never happen again. Now HEAD is again buggy and this test fails. this @julianhyde this pull can be rejected - I will log JIRA issue for this and attach the branch as a reproduction, ok?

**Comment by julianhyde** [comment]
@ptrbojko That makes sense. A PR with a test that fails before and succeeds after is always good.

**Comment by ptrbojko** [comment]
See https://issues.apache.org/jira/browse/CALCITE-2264

**Comment by ptrbojko** [comment]
@julianhyde  I've patched here [CALCITE-2264](https://issues.apache.org/jira/browse/CALCITE-2264).

**Pull request closed without merging**
