### PR TITLE
[CALCITE-5038] Making AGGREGATE_ANY_PULL_UP_CONSTANTS's test cases more rigorous

### PR DESCRIPTION
**Pull request by wojustme**
Link to JIRA: https://issues.apache.org/jira/browse/CALCITE-5038

### CODE REVIEW

**Review by hsyuan — APPROVED** [review]
LGTM

**Comment by wojustme** [comment]
@hsyuan Thanks for reviewing this pr.

**Comment by wojustme** [comment]
Hi @hsyuan 
Are there any deficiencies in this pr?
Could you merge it?
Thanks a lot.

**Review by NobiGo — COMMENTED** [review]
Why just change the column? I am  curious

**Comment by wojustme** [comment]
@NobiGo 
The `sales.emp`'s field of sal is not-null, the condition of `sal is null` always return `FALSE` in these cases.
Extracting the constants will fail, after simplifying rexnode
So, this test case may be not rigorous.

**Comment by wojustme** [comment]
These changes have been integrated into [PR-2743](https://github.com/apache/calcite/pull/2743)
I close it.

**Pull request closed without merging**
