### PR TITLE
[CALCITE-3667] EnumerableMergeJoin should not use take-while enumerat…

### PR DESCRIPTION
**Pull request by jinxing64**
…or (Jin Xing)

### CODE REVIEW

**Comment by vlsi** [comment]
Frankly speaking, I'm looking into reverting the change to `mergeJoin(...)` method:
1) Reverting the method would keep backward compatibility with linq4j API
2) The current implementation is not different from the old `mergeJoin(...).where(...)`, thus it would be better to just generate `.where(...)` code in `EnumerableMergeJoin` than alter `mergeJoin` API.

**Comment by jinxing64** [comment]
Hi @vlsi 
Thanks a lot for comment ~

1. Yes, the implementation is similar to `mergeJoin(...).where(...)`,  the output of of `mergeJoin` is `Enumerator<TResult>`, it's hard to filter values with predicate of `Predicate2<TSource, TInner>`. That's why I implement the filtering inside of `MergeJoinEnumerator`

2. For backword compatibility, shall we keep the old method of `mergeJoin` with a default `predicate`  ?

How do you think ?

**Comment by vlsi** [comment]
Please check `[CALCITE-3285] Fixup to EnumerableMergeJoinRule` commit here: https://github.com/apache/calcite/pull/1702/commits

**Comment by jinxing64** [comment]
I'm closing this PR and go by fix from PR-1702

**Pull request closed without merging**
