### PR TITLE
[CALCITE-2570] Upgrade forbiddenapis to 2.6 for JDK 11 support

### PR DESCRIPTION
**Pull request by risdenk**

### CODE REVIEW

**Comment by risdenk** [comment]
Hmmm bunch of errors about zip END header not found... This is partially through the build too not on the first module. This only happened on JDK 11 too. 

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error reading /root/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar; zip END header not found
[ERROR] /src/spark/src/main/java/org/apache/calcite/adapter/spark/SparkRel.java:[17,1] cannot access org.apache.calcite.adapter.spark
  zip END header not found
...
```

**Comment by risdenk** [comment]
Force pushed same changes with a slightly different commit message to retrigger the build.

**Comment by risdenk** [comment]
Windows failures twice now (Travis figured itself out).

```
[ERROR] Tests run: 142, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 5.891 s <<< FAILURE! - in org.apache.calcite.rel.rel2sql.RelToSqlConverterTest
[ERROR] testUnparseInStruct1(org.apache.calcite.rel.rel2sql.RelToSqlConverterTest)  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'))"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'))"
	at org.apache.calcite.rel.rel2sql.RelToSqlConverterTest.testUnparseInStruct1(RelToSqlConverterTest.java:421)
[ERROR] testUnparseInStruct2(org.apache.calcite.rel.rel2sql.RelToSqlConverterTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'), ROW(2, 'PRESIDENT'))"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'), ROW(2, 'PRESIDENT'))"
	at org.apache.calcite.rel.rel2sql.RelToSqlConverterTest.testUnparseInStruct2(RelToSqlConverterTest.java:437)
[ERROR] testUnparseIn1(org.apache.calcite.rel.rel2sql.RelToSqlConverterTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE \"DEPTNO\" IN (21)"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE \"DEPTNO\" IN (21)"
	at org.apache.calcite.rel.rel2sql.RelToSqlConverterTest.testUnparseIn1(RelToSqlConverterTest.java:396)
[ERROR] testUnparseIn2(org.apache.calcite.rel.rel2sql.RelToSqlConverterTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE \"DEPTNO\" IN (20, 21)"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE \"DEPTNO\" IN (20, 21)"
	at org.apache.calcite.rel.rel2sql.RelToSqlConverterTest.testUnparseIn2(RelToSqlConverterTest.java:407)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   RelToSqlConverterTest.testUnparseIn1:396 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE \"DEPTNO\" IN (21)"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE \"DEPTNO\" IN (21)"
[ERROR]   RelToSqlConverterTest.testUnparseIn2:407 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE \"DEPTNO\" IN (20, 21)"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE \"DEPTNO\" IN (20, 21)"
[ERROR]   RelToSqlConverterTest.testUnparseInStruct1:421 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'))"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'))"
[ERROR]   RelToSqlConverterTest.testUnparseInStruct2:437 
Expected: is "SELECT *\nFROM \"scott\".\"EMP\"\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'), ROW(2, 'PRESIDENT'))"
     but: was "SELECT *\r\nFROM \"scott\".\"EMP\"\r\nWHERE ROW(\"DEPTNO\", \"JOB\") IN (ROW(1, 'PRESIDENT'), ROW(2, 'PRESIDENT'))"
```

Looks like `\r\n` vs `\n` for string comparison. I rebased my branch on latest master in case I missed a few commits that would have fixed this.

**Comment by vlsi** [comment]
@risdenk , Windows failure is not your fault. It is to be fixed in https://github.com/apache/calcite/pull/837

**Comment by risdenk** [comment]
Ah ok thanks @vlsi

**Pull request closed without merging**
