### PR TITLE
Caused by: java.sql.SQLException: exception while executing query: Multiple entries with same key: 

### PR DESCRIPTION
**Pull request by love1693294577**
what  is it？

### CODE REVIEW

**Comment by hsyuan** [comment]
Any JIRA issue for it?

**Comment by love1693294577** [comment]
i  do not  know  .I don't know, how can this problem occur, have you encountered it before?

**Comment by love1693294577** [comment]
> Any JIRA issue for it?
i do not know .I don't know, how can this problem occur, have you encountered it before?

**Comment by hsyuan** [comment]
Closing this. Please open a JIRA issue if you think there is a bug.

**Pull request closed without merging**
