### PR TITLE
[CALCITE-1987] Implement EXTRACT for JDBC

### PR DESCRIPTION
**Pull request by pavelgubin**

### CODE REVIEW

**Comment by michaelmior** [comment]
Thanks for the contribution!

Can you combine those two commits and title the commit to reference the issue? e.g., `[CALCITE-1987] Implement EXTRACT for JDBC`. In the future, it would also be helpful if you could title PRs this way so it's easier to see what it's for.

**Comment by pavelgubin** [comment]
I should have probably updated /core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml with new plans but don't know where to take the new xml.

**Comment by michaelmior** [comment]
@julianhyde Any suggestions? I'm not familiar with this test suite. Also, just a heads up @pavelgubin that we're in release mode right now, so we won't be able to merge right away, but this looks like it will be good to go as soon as the next release is made.

**Comment by julianhyde** [comment]
@pavelgubin You should definitely have updated RelOptRulesTest.xml if your current PR gives test errors. If you submit a PR for review we assume that all tests pass, unless you state otherwise. After all what's the use of a "fix" that breaks several other tests. The plan changes could be benign, but if the new plans are less efficient then we won't accept this PR.

Read the javadoc in RelOptRulesTest.java. It describes how to update RelOptRulesTest.xml.

It sounds like @michaelmior is +1 on this change. Please fix the tests, and I will squash / rebase / re-title and commit to master after 1.14 is released.

**Comment by pavelgubin** [comment]
Thanks for the info, RelOptRulesTest.xml updated. Looking into Druid integration now.

**Pull request closed without merging**
