### PR TITLE
[CALCITE-6224] Add LOG2 function (enabled in Mysql, Spark library)

### PR DESCRIPTION
**Pull request by caicancai**

### CODE REVIEW

**Comment by caicancai** [comment]
I added tanclary as co-author

**Comment by caicancai** [comment]
I will add the log10 and log functions to Mysql.library, which I find is better to write with log2, and I will modify jira

**Review by tanclary — APPROVED** [review]
I think this looks good. Thanks for fixing all of the issues. I will approve but allow time for any other comments.

**Review by JiajunBernoulli — APPROVED** [review]

**Comment by JiajunBernoulli** [comment]
LGTM

**Comment by JiajunBernoulli** [comment]
Please squash them, we can merge it soon.

**Comment by caicancai** [comment]
> Please squash them, we can merge it soon.

done

**Comment by tanclary** [comment]
@caicancai I just squashed and merged you should find the commit in the main branch now, thanks!

**Comment by caicancai** [comment]
> @caicancai I just squashed and merged you should find the commit in the main branch now, thanks!

@tanclary I am very grateful for your help in this PR. I will soon improve the log function of mysql. Action is the best feedback.

**Pull request closed without merging**
