### PR TITLE
[CALCITE-2722] - SqlImplementor createLeftCall StackOverflowError fix

### PR DESCRIPTION
**Pull request by kolunyaa**

### CODE REVIEW

**Comment by vlsi** [comment]
@kolunyaa , Hi, that's great! Would you please add a test case that blows up previous implementation and works just fine with the fix?

**Comment by kolunyaa** [comment]
> Hi, that's great! Would you please add a test case that blows up previous implementation and works just fine with the fix?
Hi! Tests are ready.

**Comment by vlsi** [comment]
@kolunyaa , am I right you are NOT touching code in `SqlImplementor#createLeftCall`?

My idea was to add a test case that would craft "very big SQL" (or whatever) and feed it to `SqlImplementor` to see how it blows.

Of course, with your fix the test will always pass and it won't throw StackOverflow, however the test will protect the code from "accidental" refactoring to recursive code.

**Comment by kgyrtkirk** [comment]
I completely missed this - there was another PR for CALCITE-2722
I'll just close this now...

**Pull request closed without merging**
