### PR TITLE
[CALCITE-6387] Make Arrow adapter passing tests with jdk17+

### PR DESCRIPTION
**Pull request by snuyanzin**
First commit removes `add-opens` flag to reproduce the issue on gha

Second commit to fix the problem both for gha and local run

### CODE REVIEW

**Comment by snuyanzin** [comment]
@macroguo-ghy, @asolimando  could you please have a look since you were involved in the original Arrow adapter implementation/review

**Review by asolimando — APPROVED** [review]
Thanks @snuyanzin, tested locally with `17.0.9-zulu` and I don't have any error now

**Comment by macroguo-ghy** [comment]
Thanks @snuyanzin .
A minor comment: better remove `--add-opens` in    https://github.com/apache/calcite/blob/d4e88302e367b7f5a3b3da9d2e0f734320cef413/Jenkinsfile#L44-L46

**Comment by snuyanzin** [comment]
Thanks for the hint @macroguo-ghy, changed it for jenkins file as well

**Comment by snuyanzin** [comment]
Thanks for taking a look, 
I'm going to merge it

**Review by caicancai — APPROVED** [review]

**Comment by snuyanzin** [comment]
squash commits before merging

**Pull request merged**
