### PR TITLE
[CALCITE-5083] In RelBuilder.project_, do not unwrap SARGs (Vladimir Ozerov)

### PR DESCRIPTION
**Pull request by devozerov**
See [1] and [2] for the context.

[1] https://lists.apache.org/thread/chwjcrdb760xbrgtx534008kpqoxbdvp
[2] https://issues.apache.org/jira/browse/CALCITE-5083

### CODE REVIEW

**Review by asolimando — APPROVED** [review]
LGTM @devozerov, nice catch!

**Comment by asolimando** [comment]
Can we re-trigger tests since the Calcite/Avatica integration tests did not fully run?

You can achieve that via an empty commit.

**Comment by julianhyde** [comment]
Can you also add a test in RelBuilderTest?

**Comment by devozerov** [comment]
@asolimando done. @julianhyde the has been added.

**Pull request merged**
