### PR TITLE
[CALCITE-3039] In Interpreter, min() incorrectly returns maximum double value（dijkspicy）

### PR DESCRIPTION
**Pull request by dijkspicy**
Correct MinDouble class and add UT to ensure this change

### CODE REVIEW

**Comment by chunweilei** [comment]
It looks like duplicate with https://github.com/apache/calcite/pull/1191.

**Comment by dijkspicy** [comment]
> It looks like duplicate with #1191.

i forgot ut in #1191 , so i recommit this issue

**Comment by chunweilei** [comment]
You don't need to open another commit next time~~. You can find more in this doc[1].

 [1] https://calcite.apache.org/develop/#contributing

**Comment by chunweilei** [comment]
LGTM

**Comment by dijkspicy** [comment]
> You don't need to open another commit next time~~. You can find more about contributing in this doc[1].
> 
> [1] https://calcite.apache.org/develop/#contributing

OK. This is my first time to commit code to opensource repo. more to learn for me

**Comment by chunweilei** [comment]
@dijkspicy could you please add your name in parentheses at the end of the first line of the commit message?

**Comment by dijkspicy** [comment]
> @dijkspicy could you please add your name in parentheses at the end of the first line of the commit message?

Sorry, what do you mean MY NAME?

**Comment by chunweilei** [comment]
Just like `[CALCITE-3003] AssertionError when GROUP BY nested field (Will Yu)`.  The name in parentheses is your JIRA id.

**Comment by chunweilei** [comment]
You should change your commit message instead of the title of this PR. You can use `git log` to see what other commits like.

**Pull request closed without merging**
