### PR TITLE
CALCITE-1810 Allow NULL for ARRAY constructor

### PR DESCRIPTION
**Pull request by ankitsinghal**

### CODE REVIEW

**Comment by michaelmior** [comment]
It would be good to avoid the unnecessary reordering of imports to keep the history cleaner. Also, the code uses spaces instead of tabs for indentation. Finally, it would be good to have a test which exercises this code path.

**Comment by ankitsinghal** [comment]
Thanks, @michaelmior for checking. I have now updated the pull request with correct formatting and a test-case.

**Comment by michaelmior** [comment]
If you could squash that commit into your previous, that looks good to me to merge.

**Comment by ankitsinghal** [comment]
here you go @michaelmior .

**Comment by michaelmior** [comment]
Thanks!

**Pull request closed without merging**
