### PR TITLE
[CALCITE-3310] Approximate and exact aggregate calls are recognized as the same duri…

### PR DESCRIPTION
**Pull request by danny0405**
…ng sql-to-rel conversion

### CODE REVIEW

**Comment by hsyuan** [comment]
Can you add the test case in the issue?

**Comment by hsyuan** [comment]
Sorry, just noticed the test case. :)

**Comment by hsyuan** [comment]
Please change the commit title by adding JIRA issue.

**Comment by danny0405** [comment]
Thanks for the reminder @hsyuan !

**Pull request merged**
