### PR TITLE
[CALCITE-6256] Incorrect rendering of HTML on InnoDB adapter page

### PR DESCRIPTION
**Pull request by strongduanmu**
The new rendered HTML is as follows(IDEA Local preview without CSS style).

image

### CODE REVIEW

**Comment by julianhyde** [comment]
Seems to fix the problem.

I think that the "`mysqldump -d -u<username> -p<password> -h <hostname> <dbname>`" line would be better as its own code box, rather than inline; can you change it to use the highlight markup?

We don't allow commit messages with the word 'fix'. Can you change the commit message to match the jira case summary.

**Comment by strongduanmu** [comment]
@julianhyde Thank you for your advice, I will modify this pr.

**Comment by julianhyde** [comment]
You changed 'Fix' to 'Correct' in the commit message. Instead, can you change the commit message to the jira case summary? (If a commit message describes a bug, it is implied that the commit fixes the bug.)

**Comment by strongduanmu** [comment]
Thank you very much for your guidance. I will pay attention to these norms of the Calcite community so that my next contribution can be more perfect.

**Review by julianhyde — APPROVED** [review]

**Pull request merged**
