### PR TITLE
[CALCITE-1253]Create Elasticsearch adapter for Calcite

### PR DESCRIPTION
**Pull request by sbcd90**
Kindly review & accept this contribution.

### CODE REVIEW

**Comment by sbcd90** [comment]
Hello @michaelmior , Can you kindly review this PR as well? Apart from documentation, do I need to provide anything else for the initial contribution?

As is already suggested in Jira, we may need to enhance the adapter with more new features.

**Comment by michaelmior** [comment]
I think there's more than enough here feature-wise to warrant inclusion. I took a skim over the code and it looks more complete than the Cassandra adapter was when that first got merged :) I think adding the documentation should cover everything.

@julianhyde Should we be aiming to get this in for the 1.8 release?

**Comment by julianhyde** [comment]
@michaelmior This feature would be half-baked if we rushed it into 1.8. Better to take our time, make sure the architecture, tests and doc are solid before we launch. If the base is solid, it will be easy to add new features (just like you have been doing to the Cassandra adapter recently).

**Comment by michaelmior** [comment]
@julianhyde Agreed. I thought it might be worth considering since this PR looks in great shape, but there's really no need to rush things.

**Comment by sbcd90** [comment]
Hello @julianhyde , @michaelmior , I have also added documentation similar to the one in cassandra-adapter. would greatly appreciate if you can have a look now.

**Comment by michaelmior** [comment]
@sbcd90 Copying the final paragraph directly from the Cassandra documentation feels a little odd to me, but overall the documentation looks good to me. Great work!

**Comment by julianhyde** [comment]
I'm testing the adapter against the VM and reviewing the adapter now. As
@michaelmior suggests, let's try to get this into 1.8. We have a few days
to get the documentation right.

**Comment by sbcd90** [comment]
@julianhyde thanks.
@julianhyde & @michaelmior I have made some changes to the final paragraph. Please let me know if it looks fine now.

**Comment by michaelmior** [comment]
@sbcd90 Looks fine to me. Note that @julianhyde posted detailed comments on this PR on the associated [JIRA](https://issues.apache.org/jira/browse/CALCITE-1253).

**Comment by sbcd90** [comment]
@michaelmior , Thanks for pointing me to the jira. I missed it. I'll update the PR today with all the changes.

**Pull request closed without merging**
