### PR TITLE
[CALCITE-2671] GeodeFilter change to tansform Multiple Or s to IN SET…

### PR DESCRIPTION
**Pull request by chadasa**
…(Sandeep Chada)

Geode IN SET gives much higher performance than hundreds of OR statements.
Also added bug fixes to support search by DATE, TIME, TIMESTAMP fields

### CODE REVIEW

**Comment by zinking** [comment]
looks good overall

**Comment by asereda-gs** [comment]
Is it possible to separate this PR into 2 ? 
1. Geode transformation of disjunctions back into `IN`: 
```sql
 foo = 1 or foo = 2 or foo = 3
-- equivalent to (but much faster in geode) 
foo in SET(1, 2, 3)
```
([IN SET](http://geode.apache.org/docs/guide/17/developing/query_select/the_where_clause.html#the_where_clause__section_AC12146509F141378E493078540950C7) in something specific to geode)
2. Support for temporal types and searches (DATE, TIME, TIMESTAMP etc.)

**Comment by asereda-gs** [comment]
Please note that this will implementation will have to be changed once `IN` will become a flat RexCall.
Read [discussion](https://lists.apache.org/thread.html/e2c55425383fed7d7a76d452af8ecda61a74b787bdef38657ea41fe4@%3Cdev.calcite.apache.org%3E).

**Comment by chadasa** [comment]
Closing this PR and splitting it into two as suggested by Andrei

**Pull request closed without merging**
