### PR TITLE
[CALCITE-4547] Support Java 16 and 17

### PR DESCRIPTION
**Pull request by ILuffZhe**
This PR updates JDK、Gradle version and configures CI tests for JDK 16、 17.

### CODE REVIEW

**Comment by NobiGo** [comment]
@ILuffZhe Now, The CI only runs in JDK17 please confirm the Calcite can build in JDK16 local. Then we can merge this.

**Comment by ILuffZhe** [comment]
@NobiGo I'm on it already. I'll ping you after work.

**Comment by ILuffZhe** [comment]
Hi, @NobiGo . I've built the whole project with JDK 16, and it works fine. Here are the environment info:
(1) **JDK**
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

(2) **gradle**: 7.3

(3)**machine**: macOS 10.14.6

**Review by NobiGo — APPROVED** [review]
LGTM

**Pull request closed without merging**
