### PR TITLE
[CALCITE-2855] Make RelOptCluster constructor public

### PR DESCRIPTION
**Pull request by godfreyhe**
Expose RelOptCluster Constructor outside package to allow override.

### CODE REVIEW

**Comment by julianhyde** [comment]
Sounds like a bad idea.

Not least because the method you made public was deprecated.

**Comment by godfreyhe** [comment]
I had reverted some changes, only make non-deprecated constructor as public

**Comment by julianhyde** [comment]
Well, it's a bad idea for some other reasons that someone else raised.

**Comment by godfreyhe** [comment]
Hi @julianhyde, do you have any suggestion about the topic in: https://issues.apache.org/jira/browse/CALCITE-2855. Looking forward your advice, thanks very much!

**Comment by risdenk** [comment]
Going to close this PR since it looks like the conversation on JIRA went in a different direction. It can be reopened if this is the right direction.

**Pull request closed without merging**
