### PR TITLE
[CALCITE-6119] Upgrade testcontainers to 1.19.3

### PR DESCRIPTION
**Pull request by chucheng92**
One of the main features is a fixing for SELinux users (1.19.1).
https://github.com/testcontainers/testcontainers-java/pull/6294

bugfixes(1.19.3)
Register default network alias using ContainerDef 
Fix regression using GenericContainer#setImage

release notes:
https://github.com/testcontainers/testcontainers-java/releases/tag/1.19.3

### CODE REVIEW

**Comment by chucheng92** [comment]
the failed test case is Druid test.

**Comment by snuyanzin** [comment]
@chucheng92 can you please rebase and I guess it's better to bump to 1.19.3

**Comment by chucheng92** [comment]
> @chucheng92 can you please rebase and I guess it's better to bump to 1.19.3

hi @snuyanzin thanks for reviewing. updated to 1.19.3. PTAL~ if you are free.

**Review by snuyanzin — APPROVED** [review]

**Comment by chucheng92** [comment]
thanks sergey, merging...

**Pull request merged**
