### PR TITLE
[CALCITE-669] Mass removal of Java Logging for SLF4J.

### PR DESCRIPTION
**Pull request by joshelser**
Replace FINE with DEBUG, FINER and FINEST with TRACE.
Includes the slf4j-log4j12 binding for test-time. Attempts
remove all conditional logging blocks unless there is
a reason to keep them.

### CODE REVIEW

**Comment by joshelser** [comment]
Have any time to take a glance, @julianhyde?

**Comment by julianhyde** [comment]
Looks great. (It must have been a lot of work!)

The sole remaining use of java.util.logging.Logger is in UnregisteredDriver. I suppose this is intentional.

Pedantic, but the license headers for the .properties files are slightly different to those on our existing .properties files.

I'd remove the comment from the doc about migration. Can you put it in the release notes instead? Start a new section in history.md "## ... 1.7.0 / (under development)"

+1 

(But obviously, don't commit to master until I give the green light after the release.)

**Comment by joshelser** [comment]
> The sole remaining use of java.util.logging.Logger is in UnregisteredDriver. I suppose this is intentional.

Yep. This is inherited from JDBC, so I left it as-is. I think that's the right thing to do.

> Pedantic, but the license headers for the .properties files are slightly different to those on our existing .properties files.

Ah, it was a copy-paste from elsewhere. I will rectify.

> I'd remove the comment from the doc about migration. Can you put it in the release notes instead? Start a new section in history.md "## ... 1.7.0 / (under development)"

Will do.

> don't commit to master until I give the green light after the release

Great, I was going to ask if it was closed for the 1.6.0 release still :)

**Comment by joshelser** [comment]
66c5955 addresses the license headers and 8b3063e updates the website. Once I get an all-clear from you, Julian, I will squash+merge these changes. Thanks again!

**Pull request closed without merging**
