### PR TITLE
[CALCITE-6130] Transformation optimization of different physical conventions on the production of new physical nodes

### PR DESCRIPTION
**Pull request by caicancai**
[CALCITE-6130] Transformation optimization of different physical conventions on the production of new physical nodes

### CODE REVIEW

**Comment by JiajunBernoulli** [comment]
@caicancai 
May we have a unit tests? Even if it's not SQL, RelNode is ok.

**Comment by caicancai** [comment]
> @caicancai May we have a unit tests? Even if it's not SQL, RelNode is ok.

ok, thank you for your reply. Let me think about the best way to display test

**Comment by caicancai** [comment]
> @caicancai May we have a unit tests? Even if it's not SQL, RelNode is ok.

ok, thank you for your reply. Let me think about the best way to display test

**Comment by caicancai** [comment]
hi, I found that there is a pr that is similar to this pr, do I need to close this pr

**Comment by caicancai** [comment]
https://github.com/apache/calcite/pull/2452

**Pull request closed without merging**
