### PR TITLE
[CALCITE-2331] evaluation of predicate (A or B) and C fails for ES adapter

### PR DESCRIPTION
**Pull request by asereda-gs**
This PR was created against branch of #744 so you might see more diffs than expected. Please note it fixes only ES (not mongo, which is also affected).

Add new PredicateAnalyzer which uses visitor pattern to construct correct expression. The original version was copied from [Dremio project](https://github.com/dremio/dremio-oss/blob/master/plugins/elasticsearch/src/main/java/com/dremio/plugins/elastic/planning/rules/ProjectAnalyzer.java) (thanks to their team for improving calcite-ES integration)

Create internal QueryBuilders which mimics functionality of original ES API (TermQuery, BoolQuery, RangeQuery etc.)

### Introduced Regression
There is one regression in the test `testFilterRedundant`. When expressions on the same column not being optimized:
```sql
--- original
where state > 'CA' and state < 'AZ' and state = 'OK'
-- Multiple constraints on the same column. 
-- If there is an '=', it supersedes all other operators.
where state = 'OK'
```
This test is currently ignored.

### CODE REVIEW

**Comment by michaelmior** [comment]
Seems like the removal of `elasticsearch5/src/test/resources/log4j2.xml` should actually be part of #744?

**Comment by michaelmior** [comment]
Any idea how complicated it will be to fix `testFilterRedundant`? I'd certainly prefer to favour correctness over performance, but it would be good to get a sense of how challenging this would be to fix in the future.

**Comment by asereda-gs** [comment]
Re `elasticsearch5/src/test/resources/log4j2.xml` it was modified as part of  4e93a82c. So I had to remove it explicitly.

**Comment by michaelmior** [comment]
Re: "fixing" user queries - IMO, it depends on the cost of doing so. If we can without burning too many cycles or complicating things too much on the Calcite side. One of the nice things having these kinda of optimizations in Calcite if we do them cheaply is that it makes it easier to programmatically generate queries without having to think about these things.

**Comment by michaelmior** [comment]
Sorry about the closing. I accidentally closed this instead of #744. That's fixed now, but you'll have to reopen this.

**Comment by asereda-gs** [comment]
@michaelmior new PR was created: #755

**Pull request closed without merging**
