### PR TITLE
Following [CALCITE-3763] Fix slow test failure

### PR DESCRIPTION
**Pull request by DonnyZone**
Fix the test failure introduced by CALCITE-3763. Could you help to confirm it? @julianhyde

### CODE REVIEW

**Comment by danny0405** [comment]
I already gave a fix in https://github.com/apache/calcite/pull/1810.

**Comment by DonnyZone** [comment]
From my personal view, since CALCITE-3763 prunes extra projects, we'd better modify the expected plan string as you do for CALCITE-3769. On the other hand, checking “CannotPlanException” is generally used in LatticeTest to indicate match failure, therefore, checking “Assertion” seems to be meaningless.

**Comment by julianhyde** [comment]
@danny0405 and @DonnyZone sorry for the disruption due to CALCITE-3763, and thanks for fixing it. Sorry I missed that one.

While CALCITE-3763 causes plan changes I claim that they are always positive (they never add a project, sometimes slim down an existing project and sometimes remove it). In my tests, narrowing the fields used by an `Aggregate` made some big improvements in a few cases.

**Comment by danny0405** [comment]
> From my personal view, since CALCITE-3763 prunes extra projects, we'd better modify the expected plan string as you do for CALCITE-3769. On the other hand, checking “CannotPlanException” is generally used in LatticeTest to indicate match failure, checking “AssertionError” breaks this common style and seems to be meaningless.

The AssertionError expects to be introduced by CALCITE-3676, if you think it is meaningless, welcome to fire a discussion.

**Comment by DonnyZone** [comment]
It is too tiny to fire a discussion. As what you do for CALCITE-3769 (i.e., changing the expected plan string from `LogicalTableScan` to `StarTableScan`), why do we not do the same thing for `testLatticeStarTable`? Because removing this extra `Project` is the expected result of CALCITE-3763.

**Comment by danny0405** [comment]
> It is too tiny to fire a discussion. As what you do for CALCITE-3769 (i.e., changing the expected plan string from `LogicalTableScan` to `StarTableScan`), why do we not do the same thing for `testLatticeStarTable`? Because removing this extra `LogicalProject` is the expected result of CALCITE-3763.

Thanks, i re-checked the plan and you are right, please also update the AssertError to CannotPlanException.

**Comment by DonnyZone** [comment]
Thanks, updated. It seems that ES test fails easily due to timeout.

**Pull request closed without merging**
