### PR TITLE
Add testSortRemoveConstantKeyWhenOrderByIsNull on RelOptRulesTest

### PR DESCRIPTION
**Pull request by caicancai**
This test is to show that SortRemoveConstantKeys can optimize Order By null

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Comment by julianhyde** [comment]
The method needs a javadoc comment.

Why does the method name use the word 'empty'? Nothing is empty in this case.

**Comment by caicancai** [comment]
> The method needs a javadoc comment.
> 
> Why does the method name use the word 'empty'? Nothing is empty in this case.

I modified the appropriate method name and added comments and associated the previous jira case, thank you

**Comment by YiwenWu** [comment]
What is the reason for adding this test, is there a jira link?

**Comment by caicancai** [comment]
> What is the reason for adding this test, is there a jira link?

https://issues.apache.org/jira/browse/CALCITE-6440

**Review by YiwenWu — APPROVED** [review]
LGTM

**Pull request merged**
