### PR TITLE
[CALCITE-3063] Parse and process PostgreSQL posix regular expressions

### PR DESCRIPTION
**Pull request by MGelbana**

### CODE REVIEW

**Comment by michaelmior** [comment]
There's a typo in `includePosixOpertaors` that should be corrected.

**Comment by MGelbana** [comment]
Thank you for your time. Done.

**Comment by MGelbana-Incorta** [comment]
@michaelmior, is there anything else I need to do to merge this PR please ? Should I contact someone else if you're buys ?

**Comment by michaelmior** [comment]
@MGelbana Sorry for the long delay and that this didn't make it into the latest release. Merging now!

**Pull request merged**
