### PR TITLE
[CALCITE-3776] Create a Gradle task to run JdbcExample (Rui Wang)

### PR DESCRIPTION
**Pull request by amaliujia**
see: https://jira.apache.org/jira/browse/CALCITE-3776

### CODE REVIEW

**Comment by amaliujia** [comment]
@vlsi @michaelmior 

could you take a look?

**Comment by vlsi** [comment]
@amaliujia, adding a task for each Java class it not the way to proceed here.

IntelliJ IDEA executes the class just fine. I use IDEA 2020.1 EAP, however, I guess recent (e.g. 2019.x) versions should work as well.

**Comment by amaliujia** [comment]
Thanks. I found that mac intellij could just work but linux version on my corp machine does not work. 


There must because of some local environment difference.

**Comment by vlsi** [comment]
No build script modification needed as per discussion in JIRA

**Pull request closed without merging**
