### PR TITLE
[CALCITE-6207] Improve JDBC connection resource in JDBCUtils

### PR DESCRIPTION
**Pull request by xuzifu666**
Improve JDBC connection resource in JDBCUtils: not need multiple judge connection whether close

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Comment by mihaibudiu** [comment]
I have merged, then cancelled the associated commit, since the change is still under debate in JIRA.

**Comment by mihaibudiu** [comment]
The discussion in the JIRA is about the behavior in the presence of exceptions. It seems that this improvement may cause a different exception to be thrown.

**Comment by mihaibudiu** [comment]
Apparently there is no way to reopen a merged PR, so please open a new one if there is an alternate fix.

**Comment by xuzifu666** [comment]
> Apparently there is no way to reopen a merged PR, so please open a new one if there is an alternate fix.

OK，I would open a new one

**Pull request merged**
