### PR TITLE
[CALCITE-3378] AssertionError for checking RexImplication `DECIMAL` literal convert `String` literal

### PR DESCRIPTION
**Pull request by xy2953396112**
https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-3378

### CODE REVIEW

**Comment by xy2953396112** [comment]
@Julianhyde @yanlin-Lynn @zabetak @hsyuan 
Please help review this pr when you have time.

**Comment by xy2953396112** [comment]
@hsyuan 
thanks for review.

**Comment by julianhyde** [comment]
See my comments in the JIRA case.

**Comment by xy2953396112** [comment]
@julianhyde 
Thanks for comment,please help review.

**Pull request closed without merging**
