### PR TITLE
[CALCITE-6175] Upgrade opencsv version from 2.3 to 5.9

### PR DESCRIPTION
**Pull request by ymlai87416**
Move OpenCsv from 2.3 to 5.9, as 2.3 does not receive any security updates.

### CODE REVIEW

**Comment by macroguo-ghy** [comment]
Thanks for you contribution! Please fix the CI error.

**Comment by macroguo-ghy** [comment]
Hi, @ymlai87416, the CI will not run until the committer clicks the `approve` button. Therefore, as a `First-time contributor`, you cannot check if your commits are okay in this repository. I suggest that you first read the [calcite develop guide](https://calcite.apache.org/develop/) and ensure that all checks pass in your local environment. Alternatively, you can fork this project to your repository, submit a PR, and run the CI there.

**Comment by macroguo-ghy** [comment]
And I suggest that you log a JIRA case.

**Comment by ymlai87416** [comment]
Thanks for the direction.

**Comment by ymlai87416** [comment]
Close this pull request as it is not following the developer guide and difficult to review

**Pull request closed without merging**
