### PR TITLE
[MINOR] Assert can be replaced in `AbstractMaterializedViewRule#perform()`

### PR DESCRIPTION
**Pull request by JiajunBernoulli**
1.  `If` maybe better than `assert`
- old
```
assert !compensationColumnsEquiPred.isAlwaysTrue()
                || !otherCompensationPred.isAlwaysTrue()
```
- new
```
 if (compensationColumnsEquiPred.isAlwaysTrue()
        && otherCompensationPred.isAlwaysTrue()) {
      continue;
    }
```

2. Optimize code comments
- Old code comments can cause misunderstandings.
```
grep -n "// [abc]\." MaterializedViewRule.java
385:            // b. Generate union branch (query).
396:            // c. Generate union branch (view).
422:            // a. Compute final compensation predicate.
459:            // b. Generate final rewriting if possible.
```
- Here are new comments.
```
grep -n "// [abcAB]\." MaterializedViewRule.java
368:            // a. Attempt partial rewriting using union operator. This rewriting
387:            // b. Generate union branch (query).
398:            // c. Generate union branch (view).
424:            // A. Compute final compensation predicate.
461:            // B. Generate final rewriting if possible.
```

### CODE REVIEW

**Comment by JiajunBernoulli** [comment]
If there are no other suggestions, I will merge it next week.

**Review by liuyongvs — APPROVED** [review]
LGTM

**Comment by zabetak** [comment]
@JiajunBernoulli @liuyongvs Changing the way that production code behaves cannot be considered a minor contribution. This change shouldn't have gone through without a JIRA ticket. Ideally, there should be also test cases validating that we are correctly bailing out according to the new code that was added.

The minor prefix is also misleading for the release manager as well as users reading the release notes. Please keep this in mind for future changes.

See also relevant thread about minor/small contributions: https://lists.apache.org/thread/pljc1vhg6bl400qpjts3obmm9zvo9pt1

**Comment by JiajunBernoulli** [comment]
@zabetak Thanks for your message.

I will pay attention to it in the future.

**Comment by zabetak** [comment]
No big deal just letting you know :)

**Pull request merged**
