### PR TITLE
[CALCITE-6199] Trim unused fields for SNAPSHOT and SAMPLE if table ha…

### PR DESCRIPTION
**Pull request by JiajunBernoulli**
…s VIRTUAL column

### CODE REVIEW

**Comment by XuQianJin-Stars** [comment]
Thank you for this. Please complete the pr description according to the specifications.

**Comment by JiajunBernoulli** [comment]
Sorry, @XuQianJin-Stars . 
What do you mean specifications?
Can you give me a link? 
I will improve according to the requirements

**Comment by libenchao** [comment]
@JiajunBernoulli I'm not sure the label "LGTM-will-merge-soon" should be added by the author. Generally the PRs should be reviewed by peers. To find a reviewer, you can ask for review in the Jira/PR/dev@ML. Fails all those approaches, and you are confident with your changes, you can commit it since you have commit privileges.

**Comment by XuQianJin-Stars** [comment]
> Sorry, @XuQianJin-Stars . What do you mean specifications? Can you give me a link? I will improve according to the requirements

Add a simple description and jira link.

**Pull request merged**
