### PR TITLE
[CALCITE-6547] Result type inferred for STDDEV_SAMP is incorrect

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Review by NobiGo — APPROVED** [review]

**Comment by NobiGo** [comment]
According to https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/VAR_SAMP.html, VAR_SAMP has the same problem.

**Comment by NobiGo** [comment]
COVAR_SAMP、COVAR_POP have the same problem. It belongs to COVAR_REGR_FUNCTION. So I have created a new ISSUE CALCITE-6548.

**Comment by mihaibudiu** [comment]
We can solve these as part of the same pr

**Comment by NobiGo** [comment]
> We can solve these as part of the same pr

Ok. Please refine the Jira description and code.

**Review by caicancai — APPROVED** [review]
LGTM

**Pull request merged**
