### PR TITLE
[CALCITE-4331] RelOptUtil#areRowTypesEqual should compare type nullability even for ANY types

### PR DESCRIPTION
**Pull request by vlsi**

### CODE REVIEW

**Comment by Aaaaaaron** [comment]
maybe a ut should be added.

**Review by hsyuan — APPROVED** [review]
+1

**Comment by rubenada** [comment]
LGTM.
As @Aaaaaaron said, probably a unit test should be added.

**Comment by xy2953396112** [comment]
+1

**Pull request closed without merging**
