### PR TITLE
[CALCITE-6250] Limitations of MongoDB adapter are not documented

### PR DESCRIPTION
**Pull request by TheOezzi**
Add hints with restrictions for documents/filters to howto site

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]

**Comment by mihaibudiu** [comment]
The rule is for the PR name, the JIRA issue, and the commit message to be the same.

**Comment by mihaibudiu** [comment]
The titles match, but they do not match the guidelines, which require the title to describe a *problem*, and not the solution to the problem. I personally don't have a problem with the title, but I think that it's good to follow the rules set up by the project. A problem-like title would be "Limitations of MongoDB adapter are not documented"

**Comment by JiajunBernoulli** [comment]
FYI: https://calcite.apache.org/develop/

**Comment by TheOezzi** [comment]
I've adapted the commit and title according to your suggestion.

**Pull request merged**
