### PR TITLE
[CALCITE-4426] Short-circuit evaluating when comparing two "RelTraitSet"s (Jiatao Tao)

### PR DESCRIPTION
**Pull request by Aaaaaaron**

### CODE REVIEW

**Comment by Aaaaaaron** [comment]
Does anyone know about this?

* What went wrong:
Execution failed for task ':rat'.
> A failure occurred while executing org.nosphere.apache.rat.RatWork
   > Apache Rat audit failure - 1 unapproved license
     	See file:///Users/runner/work/calcite/calcite/build/reports/rat/index.html

**Comment by MalteBellmann** [comment]
Hi, 
wouldn't it be easier to read and more general to implement this short-circuit in RelTraitSet#satisfies, as it is explained in the JavaDoc that "each trait set satisfies itself"? 
With this change:

public boolean satisfies(RelTraitSet that) {
    if (this == that){
      return true;
    }

    ...now the normal check...
}

**Comment by Aaaaaaron** [comment]
> Hi, 
> wouldn't it be easier to read and more general to implement this short-circuit in RelTraitSet#satisfies, as it is explained in the JavaDoc that "each trait set satisfies itself"? 
> With this change:
> 
> ```
> public boolean satisfies(RelTraitSet that) {
>     if (this == that){
>       return true;
>     }
> 
>     // now the normal check...
> }
> ```

Yes, it's better, thanks!

**Comment by liyafan82** [comment]
LGTM. This is clearly a safe improvment.

**Comment by vlsi** [comment]
@Aaaaaaron , please remove `to improve the performance of RelSubset#getRelList` from JIRA and from the commit message.
The commit has virtually nothing to do with `RelSubset#getRelList`

**Comment by Aaaaaaron** [comment]
> @Aaaaaaron , please remove `to improve the performance of RelSubset#getRelList` from JIRA and from the commit message.
> The commit has virtually nothing to do with `RelSubset#getRelList`

Sure, in the first version, the change is in getRelList and after I update the code, I forgot to change the message, thanks @vlsi !

**Review by hsyuan — COMMENTED** [review]
`matches` can do the same as `satisfies`.
It is a legit change.

**Comment by Aaaaaaron** [comment]
Hi @amaliujia, would you please review this PR? Thanks!

**Comment by amaliujia** [comment]
LGTM

if there is no objections, I will merge this PR.

**Pull request merged**
