### PR TITLE
[CALCITE-5596] Elasticsearch adapter test fails on Apple silicon

### PR DESCRIPTION
**Pull request by coolbeevip**
* Bump jna form 5.5.0  to 5.7.0 and testcontainers from 1.15.1 to 1.17.3
   * Java Native Access issue https://github.com/java-native-access/jna/pull/1297
   * Testcontainers issue https://github.com/testcontainers/testcontainers-java/issues/3834
* Replace deprecated method getContainerIpAddress

### CODE REVIEW

**Comment by julianhyde** [comment]
I think that 'Elasticsearch adapter test fails on Apple silicon' is a good summary for CALCITE-5596, and if you agree, that should be the commit message also.

**Comment by coolbeevip** [comment]
Hi @julianhyde @snuyanzin 

I have changed the commit message, but sonar pull request failed.

**Comment by snuyanzin** [comment]
Based on[1] it seems not related to the current PR changes.


```
    Caused by: org.sonarqube.ws.client.HttpException: Error 500 on https://sonarcloud.io/api/alm_integration/show_pullrequest?project=apache_calcite&pullrequestKey=3122 : {"errors":[{"msg":"An unexpected error occurred. Please try again later."}]}
                at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:22)
                at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:88)
                at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:61)
```
[1] https://ci-builds.apache.org/blue/organizations/jenkins/Calcite%2FCalcite-sonar/detail/PR-3122/2/artifacts

**Review by snuyanzin — APPROVED** [review]

**Review by libenchao — APPROVED** [review]
The changes looks good to me, I don't have a M1 chip mac either, could anyone with a M1 mac help to verify this?

**Comment by coolbeevip** [comment]
> The changes looks good to me, I don't have a M1 chip mac either, could anyone with a M1 mac help to verify this?

This is the build log on my Mac M1 https://gist.github.com/coolbeevip/c276cf1aacd837ff55bf620a2452492a, Hope it will be helpful.

**Comment by libenchao** [comment]
@coolbeevip Thanks for your confirmation, merging!

**Pull request merged**
