### PR TITLE
[CALCITE-6083] On web site, ensure contributors file is sorted 

### PR DESCRIPTION
**Pull request by mihaibudiu**

### CODE REVIEW

**Comment by JiajunBernoulli** [comment]
@mihaibudiu , would you please rerun CI?

I think that we can merge it soon.

**Review by JiajunBernoulli — APPROVED** [review]

**Comment by mihaibudiu** [comment]
What do we do about the Druid failing tests? Is anyone working on fixing that?

**Comment by libenchao** [comment]
Druid test seems always failing after https://github.com/apache/calcite/commit/55034513b463c938035e5d2436949bbf734b84b6, I'm not sure whether it's related.

**Comment by libenchao** [comment]
I've created https://issues.apache.org/jira/browse/CALCITE-6123 to track this.

**Pull request closed without merging**
