### PR TITLE
[hotfix][docs] remove redundant brackets

### PR DESCRIPTION
**Pull request by aloyszhang**
remove redundant brackets which make the hyperlink failed in algebra.md

### CODE REVIEW

**Comment by rubenada** [comment]
Thanks for the fix @aloyszhang !

**Comment by julianhyde** [comment]
I reverted this change. We do not allow random tags like '[doc]' or '[hotfix]' in commit messages.

**Comment by rubenada** [comment]
Ok, sorry about that.
@aloyszhang if you wish, please proceed again without tags in the commit message; otherwise I can commit the fix myself.

**Comment by rubenada** [comment]
I'll fix this broken link together with https://github.com/apache/calcite/pull/1613

**Pull request merged**
