### PR TITLE
[CALCITE-4112] Refine the usage of CalciteConnectionConfig in DecorrelateProgram (Jiatao Tao)

### PR DESCRIPTION
**Pull request by Aaaaaaron**
More discussion in JIRA.

### CODE REVIEW

**Comment by julianhyde** [comment]
Commit messages should start with a capital letter, not end with '.', and should end with your name in parentheses if you are not a committer.

**Comment by julianhyde** [comment]
Consider using `Util.first()`. Then the variable can stay `final`.

Consider adding a constant `DEFAULT` in `CalciteConnectionConfigImpl`.

**Comment by Aaaaaaron** [comment]
> Consider using `Util.first()`. Then the variable can stay `final`.
> 
> Consider adding a constant `DEFAULT` in `CalciteConnectionConfigImpl`.

Thanks for your suggestion, revised.

**Comment by Aaaaaaron** [comment]
> Commit messages should start with a capital letter, not end with '.', and should end with your name in parentheses if you are not a committer.

@julianhyde Thanks for your suggestion, revised.

**Comment by Aaaaaaron** [comment]
@julianhyde I've revised my PR, would you please take a look ?

**Comment by DonnyZone** [comment]
+1

**Pull request merged**
