### PR TITLE
[CALCITE-2625] Window Frame Boundary Conditional printing based on Th…

### PR DESCRIPTION
**Pull request by kk19ag**
…e aggregate function.

### CODE REVIEW

**Comment by zinking** [comment]
looks good to me

**Comment by zinking** [comment]
looks good to me.

**Comment by julianhyde** [comment]
@kk19ag Please see my comments in https://issues.apache.org/jira/browse/CALCITE-2625 and revise the PR.

**Comment by kk19ag** [comment]
@julianhyde This is ready to review.
I commented on  [ https://issues.apache.org/jira/browse/CALCITE-2625 ](https://issues.apache.org/jira/browse/CALCITE-2625) too

**Comment by kk19ag** [comment]
@julianhyde This is ready to review.

**Pull request closed without merging**
