### PR TITLE
[CALCITE-3570] Support MutableSnapshot in MutableRel

### PR DESCRIPTION
**Pull request by xy2953396112**
Support MutableSnapshot in MutableRel.This PR implements mutual conversion between MutableSnapshot and LogicalSnapshot.

### CODE REVIEW

**Comment by jinxing64** [comment]
Can you explain in what scenario `MutableSnapshot` is needed ?

**Comment by xy2953396112** [comment]
> Can you explain in what scenario `MutableSnapshot` is needed ? Since it's not supported in SubstitutionVisitor at this moment.

i think it should be supported.
such as:
query:
`SELECT * FROM emps FOR SYSTEM_TIME AS OF TIMESTAMP '2019-12-30 12:34:56'`
mv:
`SELECT * FROM emps FOR SYSTEM_TIME AS OF TIMESTAMP '2019-12-30 12:34:56'`

in this case, it should be matched. How do you think ？

**Comment by xy2953396112** [comment]
@danny0405 @chunweilei Help review this pr when you have time, thanks.

**Comment by danny0405** [comment]
I we have no use cases for that, i suggest to close the PR.

**Comment by xy2953396112** [comment]
> I we have no use cases for that, i suggest to close the PR.

Thanks for review.

**Pull request closed without merging**
