### PR TITLE
[CALCITE-3826] UPDATE assigns wrong type to bind variables

### PR DESCRIPTION
**Pull request by danny0405**

### CODE REVIEW

**Comment by danny0405** [comment]
> LGTM
> 
> My reproducer passes with this branch.
> Tests on HerdDB pass.
> 
> I will ping my collegues to test downstream applications that suffered from this bug.
> It will be easier once you merge this change and publish the snapshots to public repository.apache.org
> 
> Thank you so much @danny0405 for fixing this issue !
> And thanks to @zabetak for helping with the reproducer

I have found the root cause commit, see the JIRA comments.

**Comment by eolivelli** [comment]
I check the comment. Good catch!

That commit is 2 months ago. It is compatibile with my story.

Do you think it is worth to add similar tests for INSERT statements?
And the usage of scalar functions in UPDATE and INSERT statements?
Update set a=lower(?)  Where...

Unfortunately very few users use Calcite for DML. We have very few test cases in Calcite codebase about DML and bind variables.

We are also lacking tests about DML with sub queries + bind variables

**Comment by danny0405** [comment]
> I check the comment. Good catch!
> 
> That commit is 2 months ago. It is compatibile with my story.
> 
> Do you think it is worth to add similar tests for INSERT statements?
> And the usage of scalar functions in UPDATE and INSERT statements?
> Update set a=lower(?) Where...
> 
> Unfortunately very few users use Calcite for DML. We have very few test cases in Calcite codebase about DML and bind variables.
> 
> We are also lacking tests about DML with sub queries + bind variables

You can log some jira issues, there would be contributors if they are interested in that. Personally i have no time for that though ~

**Comment by eolivelli** [comment]
> You can log some jira issues, there would be contributors if they are interested in that. Personally i have no time for that though ~
I agree. It is fine.
I hope I am able to work again on Calcite and I will provide such new tests

thank you again

**Pull request merged**
