### PR TITLE
[CALCITE-3740] Add FilterSetOpTransposeRule to normalize materialized…

### PR DESCRIPTION
**Pull request by xy2953396112**
… view 
JIRA:[JIRA](https://issues.apache.org/jira/browse/CALCITE-3740l)

### CODE REVIEW

**Comment by vlsi** [comment]
## Before

33m

https://github.com/apache/calcite/runs/413457579?check_suite_focus=true#step:4:393

```
        1065.8sec, 6310 completed,   0 failed,   0 skipped, org.apache.calcite.test.FoodmartTest
WARNING 1301.9sec, 6390 completed,   0 failed,   6 skipped, Gradle Test Run :core:testSlow
```

## After

37m

https://github.com/apache/calcite/pull/1762/checks?check_run_id=391078477#step:4:496

```
        1331.5sec, 6310 completed,   0 failed,   0 skipped, org.apache.calcite.test.FoodmartTest
WARNING 1519.6sec, 6390 completed,   0 failed,   6 skipped, Gradle Test Run :core:testSlow
```

It looks like a 12% degradation.

**Comment by vlsi** [comment]
This rule is bad (especially under current planner) because it increases the tree. So it can produce a runaway scenario before the planner manages to identify that the rule produces millions of equivalent relations.

I would refrain including the rule in a default configuration until we do something with the planner.
https://issues.apache.org/jira/browse/CALCITE-2223 has a very similar case.

Note: the test suite is very limited, so even if we take 12% degradation as acceptable overhead (I don't think it is, but anyway), then we would still open a door for tons of `...is infinitely matched ` scenarios :(

**Comment by hsyuan** [comment]
Just one time run doesn't say anything, it maybe volatile. The other runs spends 36m:
https://github.com/apache/calcite/runs/411987622

**Comment by vlsi** [comment]
What do you think re 2223 ?

**Comment by hsyuan** [comment]
Now I see the issue. It is indeed a problem.

**Comment by hsyuan** [comment]
Closing this due to performance issue.

**Pull request closed without merging**
