### PR TITLE
[CALCITE-2903] Exception thrown when decorrelating query with TEMPORAL TABLE

### PR DESCRIPTION
**Pull request by hsyuan**
JIRA: https://issues.apache.org/jira/browse/CALCITE-2903

### CODE REVIEW

**Comment by hsyuan** [comment]
@zhztheplayer Can you help review this PR? Thanks.

**Comment by zhztheplayer** [comment]
@hsyuan It seems that the PR works, but I slightly feel that the added method `RelDecorrelator#decorrelateRel(LogicalSnapshot rel)` does not decorrelate the input when `period` is specified. Is this by your design?

**Comment by hsyuan** [comment]
Yes.

**Comment by zhztheplayer** [comment]
Sorry for immediately deleting the comment - I got it wrong.

**Comment by hsyuan** [comment]
@zhztheplayer  Thanks for your review.

**Pull request closed without merging**
