### PR TITLE
[CALCITE-3380] implement power method in Expressions.

### PR DESCRIPTION
**Pull request by xy2953396112**
implement power method in Expressions.
before:
Extensions.todo();

### CODE REVIEW

**Comment by julianhyde** [comment]
I don't think we need this method. linq4j is tied to the java language. There is no power operator in java, therefore people should not be using the `Expressions.power` function, but instead make a method call.

Rather than ```Expressions.power(a, b)``` use ```Expressions.call(null, Math.class.getMethod("power"), a, b)```. Then I think the evaluate will be able to evaluate it without any extra work.

**Comment by xy2953396112** [comment]
> I don't think we need this method. linq4j is tied to the java language. There is no power operator in java, therefore people should not be using the `Expressions.power` function, but instead make a method call.
> 
> Rather than `Expressions.power(a, b)` use `Expressions.call(null, Math.class.getMethod("power"), a, b)`. Then I think the evaluate will be able to evaluate it without any extra work.

It is more convenient for users to use `Expressions.power(a, b)`。

**Comment by julianhyde** [comment]
I agree that it is a bit more convenient. But it goes against the philosophy of this class and package. We should not do it.

**Comment by danny0405** [comment]
Close because it is not needed.

**Pull request closed without merging**
